<?php


/**
 * This class defines the structure of the 'apns_messages' table.
 *
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Tue May  5 16:41:50 2015
 *
 *
 * This map class is used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    lib.model.map
 */
class ApnsMessageTableMap extends TableMap {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'lib.model.map.ApnsMessageTableMap';

	/**
	 * Initialize the table attributes, columns and validators
	 * Relations are not initialized by this method since they are lazy loaded
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function initialize()
	{
	  // attributes
		$this->setName('apns_messages');
		$this->setPhpName('ApnsMessage');
		$this->setClassname('ApnsMessage');
		$this->setPackage('lib.model');
		$this->setUseIdGenerator(true);
		// columns
		$this->addPrimaryKey('PID', 'Pid', 'INTEGER', true, 10, null);
		$this->addColumn('CLIENTID', 'Clientid', 'VARCHAR', true, 64, null);
		$this->addColumn('FK_DEVICE', 'FkDevice', 'INTEGER', true, 9, null);
		$this->addColumn('MESSAGE', 'Message', 'VARCHAR', true, 255, null);
		$this->addColumn('DELIVERY', 'Delivery', 'TIMESTAMP', true, null, null);
		$this->addColumn('STATUS', 'Status', 'VARCHAR', true, 12, 'queued');
		$this->addColumn('CREATED', 'Created', 'TIMESTAMP', false, null, null);
		$this->addColumn('MODIFIED', 'Modified', 'TIMESTAMP', false, null, null);
		// validators
	} // initialize()

	/**
	 * Build the RelationMap objects for this table relationships
	 */
	public function buildRelations()
	{
	} // buildRelations()

	/**
	 * 
	 * Gets the list of behaviors registered for this table
	 * 
	 * @return array Associative array (name => parameters) of behaviors
	 */
	public function getBehaviors()
	{
		return array(
			'symfony' => array('form' => 'true', 'filter' => 'true', ),
			'symfony_behaviors' => array(),
		);
	} // getBehaviors()

} // ApnsMessageTableMap
