<?php


/**
 * This class defines the structure of the 'apns_device_history' table.
 *
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Tue May  5 16:41:50 2015
 *
 *
 * This map class is used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    lib.model.map
 */
class ApnsDeviceHistoryTableMap extends TableMap {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'lib.model.map.ApnsDeviceHistoryTableMap';

	/**
	 * Initialize the table attributes, columns and validators
	 * Relations are not initialized by this method since they are lazy loaded
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function initialize()
	{
	  // attributes
		$this->setName('apns_device_history');
		$this->setPhpName('ApnsDeviceHistory');
		$this->setClassname('ApnsDeviceHistory');
		$this->setPackage('lib.model');
		$this->setUseIdGenerator(true);
		// columns
		$this->addPrimaryKey('PID', 'Pid', 'INTEGER', true, 10, null);
		$this->addColumn('CLIENTID', 'Clientid', 'VARCHAR', true, 64, null);
		$this->addColumn('APPNAME', 'Appname', 'VARCHAR', true, 255, null);
		$this->addColumn('APPVERSION', 'Appversion', 'VARCHAR', false, 25, null);
		$this->addColumn('DEVICEUID', 'Deviceuid', 'CHAR', true, 40, null);
		$this->addColumn('DEVICETOKEN', 'Devicetoken', 'CHAR', true, 64, null);
		$this->addColumn('DEVICENAME', 'Devicename', 'VARCHAR', true, 255, null);
		$this->addColumn('DEVICEMODEL', 'Devicemodel', 'VARCHAR', true, 100, null);
		$this->addColumn('DEVICEVERSION', 'Deviceversion', 'VARCHAR', true, 25, null);
		$this->addColumn('PUSHBADGE', 'Pushbadge', 'VARCHAR', false, 12, 'disabled');
		$this->addColumn('PUSHALERT', 'Pushalert', 'VARCHAR', false, 12, 'disabled');
		$this->addColumn('PUSHSOUND', 'Pushsound', 'VARCHAR', false, 12, 'disabled');
		$this->addColumn('DEVELOPMENT', 'Development', 'VARCHAR', true, 12, 'production');
		$this->addColumn('STATUS', 'Status', 'VARCHAR', true, 12, 'active');
		$this->addColumn('ARCHIVED', 'Archived', 'TIMESTAMP', true, null, null);
		$this->addColumn('CREATED', 'Created', 'TIMESTAMP', false, null, null);
		$this->addColumn('MODIFIED', 'Modified', 'TIMESTAMP', false, null, null);
		// validators
	} // initialize()

	/**
	 * Build the RelationMap objects for this table relationships
	 */
	public function buildRelations()
	{
	} // buildRelations()

	/**
	 * 
	 * Gets the list of behaviors registered for this table
	 * 
	 * @return array Associative array (name => parameters) of behaviors
	 */
	public function getBehaviors()
	{
		return array(
			'symfony' => array('form' => 'true', 'filter' => 'true', ),
			'symfony_behaviors' => array(),
		);
	} // getBehaviors()

} // ApnsDeviceHistoryTableMap
