<?php


/**
 * This class defines the structure of the 'receipt' table.
 *
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Tue May  5 16:41:51 2015
 *
 *
 * This map class is used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    lib.model.map
 */
class ReceiptTableMap extends TableMap {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'lib.model.map.ReceiptTableMap';

	/**
	 * Initialize the table attributes, columns and validators
	 * Relations are not initialized by this method since they are lazy loaded
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function initialize()
	{
	  // attributes
		$this->setName('receipt');
		$this->setPhpName('Receipt');
		$this->setClassname('Receipt');
		$this->setPackage('lib.model');
		$this->setUseIdGenerator(true);
		// columns
		$this->addPrimaryKey('ID', 'Id', 'INTEGER', true, null, null);
		$this->addColumn('CREATED_AT', 'CreatedAt', 'TIMESTAMP', false, null, null);
		$this->addColumn('UPDATED_AT', 'UpdatedAt', 'TIMESTAMP', false, null, null);
		$this->addColumn('APPLICATION_ID', 'ApplicationId', 'VARCHAR', true, 255, null);
		$this->addColumn('QUANTITY', 'Quantity', 'VARCHAR', false, 10, null);
		$this->addColumn('PRODUCT_ID', 'ProductId', 'VARCHAR', false, 255, null);
		$this->addColumn('RECEIPT_TYPE', 'ReceiptType', 'VARCHAR', false, 30, null);
		$this->addColumn('TRANSACTION_ID', 'TransactionId', 'VARCHAR', true, 250, '');
		$this->addColumn('USER_ID', 'UserId', 'VARCHAR', true, 255, '');
		$this->addColumn('PURCHASE_DATE', 'PurchaseDate', 'VARCHAR', false, 50, null);
		$this->addColumn('ORIGINAL_TRANSACTION_ID', 'OriginalTransactionId', 'VARCHAR', false, 100, null);
		$this->addColumn('ORIGINAL_PURCHASE_DATE', 'OriginalPurchaseDate', 'VARCHAR', false, 50, null);
		$this->addColumn('APP_ITEM_ID', 'AppItemId', 'VARCHAR', false, 150, null);
		$this->addColumn('VERSION_EXTERNAL_IDENTIFIER', 'VersionExternalIdentifier', 'VARCHAR', false, 50, null);
		$this->addColumn('BID', 'Bid', 'VARCHAR', false, 50, null);
		$this->addColumn('BVRS', 'Bvrs', 'VARCHAR', false, 50, null);
		$this->addColumn('BASE64_RECEIPT', 'Base64Receipt', 'LONGVARCHAR', false, null, null);
		// validators
	} // initialize()

	/**
	 * Build the RelationMap objects for this table relationships
	 */
	public function buildRelations()
	{
	} // buildRelations()

	/**
	 * 
	 * Gets the list of behaviors registered for this table
	 * 
	 * @return array Associative array (name => parameters) of behaviors
	 */
	public function getBehaviors()
	{
		return array(
			'symfony' => array('form' => 'true', 'filter' => 'true', ),
			'symfony_behaviors' => array(),
			'symfony_timestampable' => array('create_column' => 'created_at', 'update_column' => 'updated_at', ),
		);
	} // getBehaviors()

} // ReceiptTableMap
