<?php

/**
 * Base static class for performing query and update operations on the 'apns_device_history' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Tue May  5 16:41:50 2015
 *
 * @package    lib.model.om
 */
abstract class BaseApnsDeviceHistoryPeer {

	/** the default database name for this class */
	const DATABASE_NAME = 'propel';

	/** the table name for this class */
	const TABLE_NAME = 'apns_device_history';

	/** the related Propel class for this table */
	const OM_CLASS = 'ApnsDeviceHistory';

	/** A class that can be returned by this peer. */
	const CLASS_DEFAULT = 'lib.model.ApnsDeviceHistory';

	/** the related TableMap class for this table */
	const TM_CLASS = 'ApnsDeviceHistoryTableMap';
	
	/** The total number of columns. */
	const NUM_COLUMNS = 17;

	/** The number of lazy-loaded columns. */
	const NUM_LAZY_LOAD_COLUMNS = 0;

	/** the column name for the PID field */
	const PID = 'apns_device_history.PID';

	/** the column name for the CLIENTID field */
	const CLIENTID = 'apns_device_history.CLIENTID';

	/** the column name for the APPNAME field */
	const APPNAME = 'apns_device_history.APPNAME';

	/** the column name for the APPVERSION field */
	const APPVERSION = 'apns_device_history.APPVERSION';

	/** the column name for the DEVICEUID field */
	const DEVICEUID = 'apns_device_history.DEVICEUID';

	/** the column name for the DEVICETOKEN field */
	const DEVICETOKEN = 'apns_device_history.DEVICETOKEN';

	/** the column name for the DEVICENAME field */
	const DEVICENAME = 'apns_device_history.DEVICENAME';

	/** the column name for the DEVICEMODEL field */
	const DEVICEMODEL = 'apns_device_history.DEVICEMODEL';

	/** the column name for the DEVICEVERSION field */
	const DEVICEVERSION = 'apns_device_history.DEVICEVERSION';

	/** the column name for the PUSHBADGE field */
	const PUSHBADGE = 'apns_device_history.PUSHBADGE';

	/** the column name for the PUSHALERT field */
	const PUSHALERT = 'apns_device_history.PUSHALERT';

	/** the column name for the PUSHSOUND field */
	const PUSHSOUND = 'apns_device_history.PUSHSOUND';

	/** the column name for the DEVELOPMENT field */
	const DEVELOPMENT = 'apns_device_history.DEVELOPMENT';

	/** the column name for the STATUS field */
	const STATUS = 'apns_device_history.STATUS';

	/** the column name for the ARCHIVED field */
	const ARCHIVED = 'apns_device_history.ARCHIVED';

	/** the column name for the CREATED field */
	const CREATED = 'apns_device_history.CREATED';

	/** the column name for the MODIFIED field */
	const MODIFIED = 'apns_device_history.MODIFIED';

	/**
	 * An identiy map to hold any loaded instances of ApnsDeviceHistory objects.
	 * This must be public so that other peer classes can access this when hydrating from JOIN
	 * queries.
	 * @var        array ApnsDeviceHistory[]
	 */
	public static $instances = array();


	// symfony behavior
	
	/**
	 * Indicates whether the current model includes I18N.
	 */
	const IS_I18N = false;

	/**
	 * holds an array of fieldnames
	 *
	 * first dimension keys are the type constants
	 * e.g. self::$fieldNames[self::TYPE_PHPNAME][0] = 'Id'
	 */
	private static $fieldNames = array (
		BasePeer::TYPE_PHPNAME => array ('Pid', 'Clientid', 'Appname', 'Appversion', 'Deviceuid', 'Devicetoken', 'Devicename', 'Devicemodel', 'Deviceversion', 'Pushbadge', 'Pushalert', 'Pushsound', 'Development', 'Status', 'Archived', 'Created', 'Modified', ),
		BasePeer::TYPE_STUDLYPHPNAME => array ('pid', 'clientid', 'appname', 'appversion', 'deviceuid', 'devicetoken', 'devicename', 'devicemodel', 'deviceversion', 'pushbadge', 'pushalert', 'pushsound', 'development', 'status', 'archived', 'created', 'modified', ),
		BasePeer::TYPE_COLNAME => array (self::PID, self::CLIENTID, self::APPNAME, self::APPVERSION, self::DEVICEUID, self::DEVICETOKEN, self::DEVICENAME, self::DEVICEMODEL, self::DEVICEVERSION, self::PUSHBADGE, self::PUSHALERT, self::PUSHSOUND, self::DEVELOPMENT, self::STATUS, self::ARCHIVED, self::CREATED, self::MODIFIED, ),
		BasePeer::TYPE_FIELDNAME => array ('pid', 'clientid', 'appname', 'appversion', 'deviceuid', 'devicetoken', 'devicename', 'devicemodel', 'deviceversion', 'pushbadge', 'pushalert', 'pushsound', 'development', 'status', 'archived', 'created', 'modified', ),
		BasePeer::TYPE_NUM => array (0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, )
	);

	/**
	 * holds an array of keys for quick access to the fieldnames array
	 *
	 * first dimension keys are the type constants
	 * e.g. self::$fieldNames[BasePeer::TYPE_PHPNAME]['Id'] = 0
	 */
	private static $fieldKeys = array (
		BasePeer::TYPE_PHPNAME => array ('Pid' => 0, 'Clientid' => 1, 'Appname' => 2, 'Appversion' => 3, 'Deviceuid' => 4, 'Devicetoken' => 5, 'Devicename' => 6, 'Devicemodel' => 7, 'Deviceversion' => 8, 'Pushbadge' => 9, 'Pushalert' => 10, 'Pushsound' => 11, 'Development' => 12, 'Status' => 13, 'Archived' => 14, 'Created' => 15, 'Modified' => 16, ),
		BasePeer::TYPE_STUDLYPHPNAME => array ('pid' => 0, 'clientid' => 1, 'appname' => 2, 'appversion' => 3, 'deviceuid' => 4, 'devicetoken' => 5, 'devicename' => 6, 'devicemodel' => 7, 'deviceversion' => 8, 'pushbadge' => 9, 'pushalert' => 10, 'pushsound' => 11, 'development' => 12, 'status' => 13, 'archived' => 14, 'created' => 15, 'modified' => 16, ),
		BasePeer::TYPE_COLNAME => array (self::PID => 0, self::CLIENTID => 1, self::APPNAME => 2, self::APPVERSION => 3, self::DEVICEUID => 4, self::DEVICETOKEN => 5, self::DEVICENAME => 6, self::DEVICEMODEL => 7, self::DEVICEVERSION => 8, self::PUSHBADGE => 9, self::PUSHALERT => 10, self::PUSHSOUND => 11, self::DEVELOPMENT => 12, self::STATUS => 13, self::ARCHIVED => 14, self::CREATED => 15, self::MODIFIED => 16, ),
		BasePeer::TYPE_FIELDNAME => array ('pid' => 0, 'clientid' => 1, 'appname' => 2, 'appversion' => 3, 'deviceuid' => 4, 'devicetoken' => 5, 'devicename' => 6, 'devicemodel' => 7, 'deviceversion' => 8, 'pushbadge' => 9, 'pushalert' => 10, 'pushsound' => 11, 'development' => 12, 'status' => 13, 'archived' => 14, 'created' => 15, 'modified' => 16, ),
		BasePeer::TYPE_NUM => array (0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, )
	);

	/**
	 * Translates a fieldname to another type
	 *
	 * @param      string $name field name
	 * @param      string $fromType One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                         BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @param      string $toType   One of the class type constants
	 * @return     string translated name of the field.
	 * @throws     PropelException - if the specified name could not be found in the fieldname mappings.
	 */
	static public function translateFieldName($name, $fromType, $toType)
	{
		$toNames = self::getFieldNames($toType);
		$key = isset(self::$fieldKeys[$fromType][$name]) ? self::$fieldKeys[$fromType][$name] : null;
		if ($key === null) {
			throw new PropelException("'$name' could not be found in the field names of type '$fromType'. These are: " . print_r(self::$fieldKeys[$fromType], true));
		}
		return $toNames[$key];
	}

	/**
	 * Returns an array of field names.
	 *
	 * @param      string $type The type of fieldnames to return:
	 *                      One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                      BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     array A list of field names
	 */

	static public function getFieldNames($type = BasePeer::TYPE_PHPNAME)
	{
		if (!array_key_exists($type, self::$fieldNames)) {
			throw new PropelException('Method getFieldNames() expects the parameter $type to be one of the class constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME, BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM. ' . $type . ' was given.');
		}
		return self::$fieldNames[$type];
	}

	/**
	 * Convenience method which changes table.column to alias.column.
	 *
	 * Using this method you can maintain SQL abstraction while using column aliases.
	 * <code>
	 *		$c->addAlias("alias1", TablePeer::TABLE_NAME);
	 *		$c->addJoin(TablePeer::alias("alias1", TablePeer::PRIMARY_KEY_COLUMN), TablePeer::PRIMARY_KEY_COLUMN);
	 * </code>
	 * @param      string $alias The alias for the current table.
	 * @param      string $column The column name for current table. (i.e. ApnsDeviceHistoryPeer::COLUMN_NAME).
	 * @return     string
	 */
	public static function alias($alias, $column)
	{
		return str_replace(ApnsDeviceHistoryPeer::TABLE_NAME.'.', $alias.'.', $column);
	}

	/**
	 * Add all the columns needed to create a new object.
	 *
	 * Note: any columns that were marked with lazyLoad="true" in the
	 * XML schema will not be added to the select list and only loaded
	 * on demand.
	 *
	 * @param      criteria object containing the columns to add.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function addSelectColumns(Criteria $criteria)
	{
		$criteria->addSelectColumn(ApnsDeviceHistoryPeer::PID);
		$criteria->addSelectColumn(ApnsDeviceHistoryPeer::CLIENTID);
		$criteria->addSelectColumn(ApnsDeviceHistoryPeer::APPNAME);
		$criteria->addSelectColumn(ApnsDeviceHistoryPeer::APPVERSION);
		$criteria->addSelectColumn(ApnsDeviceHistoryPeer::DEVICEUID);
		$criteria->addSelectColumn(ApnsDeviceHistoryPeer::DEVICETOKEN);
		$criteria->addSelectColumn(ApnsDeviceHistoryPeer::DEVICENAME);
		$criteria->addSelectColumn(ApnsDeviceHistoryPeer::DEVICEMODEL);
		$criteria->addSelectColumn(ApnsDeviceHistoryPeer::DEVICEVERSION);
		$criteria->addSelectColumn(ApnsDeviceHistoryPeer::PUSHBADGE);
		$criteria->addSelectColumn(ApnsDeviceHistoryPeer::PUSHALERT);
		$criteria->addSelectColumn(ApnsDeviceHistoryPeer::PUSHSOUND);
		$criteria->addSelectColumn(ApnsDeviceHistoryPeer::DEVELOPMENT);
		$criteria->addSelectColumn(ApnsDeviceHistoryPeer::STATUS);
		$criteria->addSelectColumn(ApnsDeviceHistoryPeer::ARCHIVED);
		$criteria->addSelectColumn(ApnsDeviceHistoryPeer::CREATED);
		$criteria->addSelectColumn(ApnsDeviceHistoryPeer::MODIFIED);
	}

	/**
	 * Returns the number of rows matching criteria.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct Whether to select only distinct columns; deprecated: use Criteria->setDistinct() instead.
	 * @param      PropelPDO $con
	 * @return     int Number of matching rows.
	 */
	public static function doCount(Criteria $criteria, $distinct = false, PropelPDO $con = null)
	{
		// we may modify criteria, so copy it first
		$criteria = clone $criteria;

		// We need to set the primary table name, since in the case that there are no WHERE columns
		// it will be impossible for the BasePeer::createSelectSql() method to determine which
		// tables go into the FROM clause.
		$criteria->setPrimaryTableName(ApnsDeviceHistoryPeer::TABLE_NAME);

		if ($distinct && !in_array(Criteria::DISTINCT, $criteria->getSelectModifiers())) {
			$criteria->setDistinct();
		}

		if (!$criteria->hasSelectClause()) {
			ApnsDeviceHistoryPeer::addSelectColumns($criteria);
		}

		$criteria->clearOrderByColumns(); // ORDER BY won't ever affect the count
		$criteria->setDbName(self::DATABASE_NAME); // Set the correct dbName

		if ($con === null) {
			$con = Propel::getConnection(ApnsDeviceHistoryPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}
		// symfony_behaviors behavior
		foreach (sfMixer::getCallables(self::getMixerPreSelectHook(__FUNCTION__)) as $sf_hook)
		{
		  call_user_func($sf_hook, 'BaseApnsDeviceHistoryPeer', $criteria, $con);
		}

		// BasePeer returns a PDOStatement
		$stmt = BasePeer::doCount($criteria, $con);

		if ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$count = (int) $row[0];
		} else {
			$count = 0; // no rows returned; we infer that means 0 matches.
		}
		$stmt->closeCursor();
		return $count;
	}
	/**
	 * Method to select one object from the DB.
	 *
	 * @param      Criteria $criteria object used to create the SELECT statement.
	 * @param      PropelPDO $con
	 * @return     ApnsDeviceHistory
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doSelectOne(Criteria $criteria, PropelPDO $con = null)
	{
		$critcopy = clone $criteria;
		$critcopy->setLimit(1);
		$objects = ApnsDeviceHistoryPeer::doSelect($critcopy, $con);
		if ($objects) {
			return $objects[0];
		}
		return null;
	}
	/**
	 * Method to do selects.
	 *
	 * @param      Criteria $criteria The Criteria object used to build the SELECT statement.
	 * @param      PropelPDO $con
	 * @return     array Array of selected Objects
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doSelect(Criteria $criteria, PropelPDO $con = null)
	{
		return ApnsDeviceHistoryPeer::populateObjects(ApnsDeviceHistoryPeer::doSelectStmt($criteria, $con));
	}
	/**
	 * Prepares the Criteria object and uses the parent doSelect() method to execute a PDOStatement.
	 *
	 * Use this method directly if you want to work with an executed statement durirectly (for example
	 * to perform your own object hydration).
	 *
	 * @param      Criteria $criteria The Criteria object used to build the SELECT statement.
	 * @param      PropelPDO $con The connection to use
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 * @return     PDOStatement The executed PDOStatement object.
	 * @see        BasePeer::doSelect()
	 */
	public static function doSelectStmt(Criteria $criteria, PropelPDO $con = null)
	{
		if ($con === null) {
			$con = Propel::getConnection(ApnsDeviceHistoryPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		if (!$criteria->hasSelectClause()) {
			$criteria = clone $criteria;
			ApnsDeviceHistoryPeer::addSelectColumns($criteria);
		}

		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);
		// symfony_behaviors behavior
		foreach (sfMixer::getCallables(self::getMixerPreSelectHook(__FUNCTION__)) as $sf_hook)
		{
		  call_user_func($sf_hook, 'BaseApnsDeviceHistoryPeer', $criteria, $con);
		}


		// BasePeer returns a PDOStatement
		return BasePeer::doSelect($criteria, $con);
	}
	/**
	 * Adds an object to the instance pool.
	 *
	 * Propel keeps cached copies of objects in an instance pool when they are retrieved
	 * from the database.  In some cases -- especially when you override doSelect*()
	 * methods in your stub classes -- you may need to explicitly add objects
	 * to the cache in order to ensure that the same objects are always returned by doSelect*()
	 * and retrieveByPK*() calls.
	 *
	 * @param      ApnsDeviceHistory $value A ApnsDeviceHistory object.
	 * @param      string $key (optional) key to use for instance map (for performance boost if key was already calculated externally).
	 */
	public static function addInstanceToPool(ApnsDeviceHistory $obj, $key = null)
	{
		if (Propel::isInstancePoolingEnabled()) {
			if ($key === null) {
				$key = (string) $obj->getPid();
			} // if key === null
			self::$instances[$key] = $obj;
		}
	}

	/**
	 * Removes an object from the instance pool.
	 *
	 * Propel keeps cached copies of objects in an instance pool when they are retrieved
	 * from the database.  In some cases -- especially when you override doDelete
	 * methods in your stub classes -- you may need to explicitly remove objects
	 * from the cache in order to prevent returning objects that no longer exist.
	 *
	 * @param      mixed $value A ApnsDeviceHistory object or a primary key value.
	 */
	public static function removeInstanceFromPool($value)
	{
		if (Propel::isInstancePoolingEnabled() && $value !== null) {
			if (is_object($value) && $value instanceof ApnsDeviceHistory) {
				$key = (string) $value->getPid();
			} elseif (is_scalar($value)) {
				// assume we've been passed a primary key
				$key = (string) $value;
			} else {
				$e = new PropelException("Invalid value passed to removeInstanceFromPool().  Expected primary key or ApnsDeviceHistory object; got " . (is_object($value) ? get_class($value) . ' object.' : var_export($value,true)));
				throw $e;
			}

			unset(self::$instances[$key]);
		}
	} // removeInstanceFromPool()

	/**
	 * Retrieves a string version of the primary key from the DB resultset row that can be used to uniquely identify a row in this table.
	 *
	 * For tables with a single-column primary key, that simple pkey value will be returned.  For tables with
	 * a multi-column primary key, a serialize()d version of the primary key will be returned.
	 *
	 * @param      string $key The key (@see getPrimaryKeyHash()) for this instance.
	 * @return     ApnsDeviceHistory Found object or NULL if 1) no instance exists for specified key or 2) instance pooling has been disabled.
	 * @see        getPrimaryKeyHash()
	 */
	public static function getInstanceFromPool($key)
	{
		if (Propel::isInstancePoolingEnabled()) {
			if (isset(self::$instances[$key])) {
				return self::$instances[$key];
			}
		}
		return null; // just to be explicit
	}
	
	/**
	 * Clear the instance pool.
	 *
	 * @return     void
	 */
	public static function clearInstancePool()
	{
		self::$instances = array();
	}
	
	/**
	 * Method to invalidate the instance pool of all tables related to apns_device_history
	 * by a foreign key with ON DELETE CASCADE
	 */
	public static function clearRelatedInstancePool()
	{
	}

	/**
	 * Retrieves a string version of the primary key from the DB resultset row that can be used to uniquely identify a row in this table.
	 *
	 * For tables with a single-column primary key, that simple pkey value will be returned.  For tables with
	 * a multi-column primary key, a serialize()d version of the primary key will be returned.
	 *
	 * @param      array $row PropelPDO resultset row.
	 * @param      int $startcol The 0-based offset for reading from the resultset row.
	 * @return     string A string version of PK or NULL if the components of primary key in result array are all null.
	 */
	public static function getPrimaryKeyHashFromRow($row, $startcol = 0)
	{
		// If the PK cannot be derived from the row, return NULL.
		if ($row[$startcol] === null) {
			return null;
		}
		return (string) $row[$startcol];
	}

	/**
	 * The returned array will contain objects of the default type or
	 * objects that inherit from the default.
	 *
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function populateObjects(PDOStatement $stmt)
	{
		$results = array();
	
		// set the class once to avoid overhead in the loop
		$cls = ApnsDeviceHistoryPeer::getOMClass(false);
		// populate the object(s)
		while ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$key = ApnsDeviceHistoryPeer::getPrimaryKeyHashFromRow($row, 0);
			if (null !== ($obj = ApnsDeviceHistoryPeer::getInstanceFromPool($key))) {
				// We no longer rehydrate the object, since this can cause data loss.
				// See http://propel.phpdb.org/trac/ticket/509
				// $obj->hydrate($row, 0, true); // rehydrate
				$results[] = $obj;
			} else {
				$obj = new $cls();
				$obj->hydrate($row);
				$results[] = $obj;
				ApnsDeviceHistoryPeer::addInstanceToPool($obj, $key);
			} // if key exists
		}
		$stmt->closeCursor();
		return $results;
	}
	/**
	 * Returns the TableMap related to this peer.
	 * This method is not needed for general use but a specific application could have a need.
	 * @return     TableMap
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function getTableMap()
	{
		return Propel::getDatabaseMap(self::DATABASE_NAME)->getTable(self::TABLE_NAME);
	}

	/**
	 * Add a TableMap instance to the database for this peer class.
	 */
	public static function buildTableMap()
	{
	  $dbMap = Propel::getDatabaseMap(BaseApnsDeviceHistoryPeer::DATABASE_NAME);
	  if (!$dbMap->hasTable(BaseApnsDeviceHistoryPeer::TABLE_NAME))
	  {
	    $dbMap->addTableObject(new ApnsDeviceHistoryTableMap());
	  }
	}

	/**
	 * The class that the Peer will make instances of.
	 *
	 * If $withPrefix is true, the returned path
	 * uses a dot-path notation which is tranalted into a path
	 * relative to a location on the PHP include_path.
	 * (e.g. path.to.MyClass -> 'path/to/MyClass.php')
	 *
	 * @param      boolean  Whether or not to return the path wit hthe class name 
	 * @return     string path.to.ClassName
	 */
	public static function getOMClass($withPrefix = true)
	{
		return $withPrefix ? ApnsDeviceHistoryPeer::CLASS_DEFAULT : ApnsDeviceHistoryPeer::OM_CLASS;
	}

	/**
	 * Method perform an INSERT on the database, given a ApnsDeviceHistory or Criteria object.
	 *
	 * @param      mixed $values Criteria or ApnsDeviceHistory object containing data that is used to create the INSERT statement.
	 * @param      PropelPDO $con the PropelPDO connection to use
	 * @return     mixed The new primary key.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doInsert($values, PropelPDO $con = null)
	{
    // symfony_behaviors behavior
    foreach (sfMixer::getCallables('BaseApnsDeviceHistoryPeer:doInsert:pre') as $sf_hook)
    {
      if (false !== $sf_hook_retval = call_user_func($sf_hook, 'BaseApnsDeviceHistoryPeer', $values, $con))
      {
        return $sf_hook_retval;
      }
    }

		if ($con === null) {
			$con = Propel::getConnection(ApnsDeviceHistoryPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}

		if ($values instanceof Criteria) {
			$criteria = clone $values; // rename for clarity
		} else {
			$criteria = $values->buildCriteria(); // build Criteria from ApnsDeviceHistory object
		}

		if ($criteria->containsKey(ApnsDeviceHistoryPeer::PID) && $criteria->keyContainsValue(ApnsDeviceHistoryPeer::PID) ) {
			throw new PropelException('Cannot insert a value for auto-increment primary key ('.ApnsDeviceHistoryPeer::PID.')');
		}


		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		try {
			// use transaction because $criteria could contain info
			// for more than one table (I guess, conceivably)
			$con->beginTransaction();
			$pk = BasePeer::doInsert($criteria, $con);
			$con->commit();
		} catch(PropelException $e) {
			$con->rollBack();
			throw $e;
		}

    // symfony_behaviors behavior
    foreach (sfMixer::getCallables('BaseApnsDeviceHistoryPeer:doInsert:post') as $sf_hook)
    {
      call_user_func($sf_hook, 'BaseApnsDeviceHistoryPeer', $values, $con, $pk);
    }

		return $pk;
	}

	/**
	 * Method perform an UPDATE on the database, given a ApnsDeviceHistory or Criteria object.
	 *
	 * @param      mixed $values Criteria or ApnsDeviceHistory object containing data that is used to create the UPDATE statement.
	 * @param      PropelPDO $con The connection to use (specify PropelPDO connection object to exert more control over transactions).
	 * @return     int The number of affected rows (if supported by underlying database driver).
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doUpdate($values, PropelPDO $con = null)
	{
    // symfony_behaviors behavior
    foreach (sfMixer::getCallables('BaseApnsDeviceHistoryPeer:doUpdate:pre') as $sf_hook)
    {
      if (false !== $sf_hook_retval = call_user_func($sf_hook, 'BaseApnsDeviceHistoryPeer', $values, $con))
      {
        return $sf_hook_retval;
      }
    }

		if ($con === null) {
			$con = Propel::getConnection(ApnsDeviceHistoryPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}

		$selectCriteria = new Criteria(self::DATABASE_NAME);

		if ($values instanceof Criteria) {
			$criteria = clone $values; // rename for clarity

			$comparison = $criteria->getComparison(ApnsDeviceHistoryPeer::PID);
			$selectCriteria->add(ApnsDeviceHistoryPeer::PID, $criteria->remove(ApnsDeviceHistoryPeer::PID), $comparison);

		} else { // $values is ApnsDeviceHistory object
			$criteria = $values->buildCriteria(); // gets full criteria
			$selectCriteria = $values->buildPkeyCriteria(); // gets criteria w/ primary key(s)
		}

		// set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		$ret = BasePeer::doUpdate($selectCriteria, $criteria, $con);

    // symfony_behaviors behavior
    foreach (sfMixer::getCallables('BaseApnsDeviceHistoryPeer:doUpdate:post') as $sf_hook)
    {
      call_user_func($sf_hook, 'BaseApnsDeviceHistoryPeer', $values, $con, $ret);
    }

    return $ret;
	}

	/**
	 * Method to DELETE all rows from the apns_device_history table.
	 *
	 * @return     int The number of affected rows (if supported by underlying database driver).
	 */
	public static function doDeleteAll($con = null)
	{
		if ($con === null) {
			$con = Propel::getConnection(ApnsDeviceHistoryPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		$affectedRows = 0; // initialize var to track total num of affected rows
		try {
			// use transaction because $criteria could contain info
			// for more than one table or we could emulating ON DELETE CASCADE, etc.
			$con->beginTransaction();
			$affectedRows += BasePeer::doDeleteAll(ApnsDeviceHistoryPeer::TABLE_NAME, $con);
			// Because this db requires some delete cascade/set null emulation, we have to
			// clear the cached instance *after* the emulation has happened (since
			// instances get re-added by the select statement contained therein).
			ApnsDeviceHistoryPeer::clearInstancePool();
			ApnsDeviceHistoryPeer::clearRelatedInstancePool();
			$con->commit();
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Method perform a DELETE on the database, given a ApnsDeviceHistory or Criteria object OR a primary key value.
	 *
	 * @param      mixed $values Criteria or ApnsDeviceHistory object or primary key or array of primary keys
	 *              which is used to create the DELETE statement
	 * @param      PropelPDO $con the connection to use
	 * @return     int 	The number of affected rows (if supported by underlying database driver).  This includes CASCADE-related rows
	 *				if supported by native driver or if emulated using Propel.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	 public static function doDelete($values, PropelPDO $con = null)
	 {
		if ($con === null) {
			$con = Propel::getConnection(ApnsDeviceHistoryPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}

		if ($values instanceof Criteria) {
			// invalidate the cache for all objects of this type, since we have no
			// way of knowing (without running a query) what objects should be invalidated
			// from the cache based on this Criteria.
			ApnsDeviceHistoryPeer::clearInstancePool();
			// rename for clarity
			$criteria = clone $values;
		} elseif ($values instanceof ApnsDeviceHistory) { // it's a model object
			// invalidate the cache for this single object
			ApnsDeviceHistoryPeer::removeInstanceFromPool($values);
			// create criteria based on pk values
			$criteria = $values->buildPkeyCriteria();
		} else { // it's a primary key, or an array of pks
			$criteria = new Criteria(self::DATABASE_NAME);
			$criteria->add(ApnsDeviceHistoryPeer::PID, (array) $values, Criteria::IN);
			// invalidate the cache for this object(s)
			foreach ((array) $values as $singleval) {
				ApnsDeviceHistoryPeer::removeInstanceFromPool($singleval);
			}
		}

		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		$affectedRows = 0; // initialize var to track total num of affected rows

		try {
			// use transaction because $criteria could contain info
			// for more than one table or we could emulating ON DELETE CASCADE, etc.
			$con->beginTransaction();
			
			$affectedRows += BasePeer::doDelete($criteria, $con);
			ApnsDeviceHistoryPeer::clearRelatedInstancePool();
			$con->commit();
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Validates all modified columns of given ApnsDeviceHistory object.
	 * If parameter $columns is either a single column name or an array of column names
	 * than only those columns are validated.
	 *
	 * NOTICE: This does not apply to primary or foreign keys for now.
	 *
	 * @param      ApnsDeviceHistory $obj The object to validate.
	 * @param      mixed $cols Column name or array of column names.
	 *
	 * @return     mixed TRUE if all columns are valid or the error message of the first invalid column.
	 */
	public static function doValidate(ApnsDeviceHistory $obj, $cols = null)
	{
		$columns = array();

		if ($cols) {
			$dbMap = Propel::getDatabaseMap(ApnsDeviceHistoryPeer::DATABASE_NAME);
			$tableMap = $dbMap->getTable(ApnsDeviceHistoryPeer::TABLE_NAME);

			if (! is_array($cols)) {
				$cols = array($cols);
			}

			foreach ($cols as $colName) {
				if ($tableMap->containsColumn($colName)) {
					$get = 'get' . $tableMap->getColumn($colName)->getPhpName();
					$columns[$colName] = $obj->$get();
				}
			}
		} else {

		}

		return BasePeer::doValidate(ApnsDeviceHistoryPeer::DATABASE_NAME, ApnsDeviceHistoryPeer::TABLE_NAME, $columns);
	}

	/**
	 * Retrieve a single object by pkey.
	 *
	 * @param      int $pk the primary key.
	 * @param      PropelPDO $con the connection to use
	 * @return     ApnsDeviceHistory
	 */
	public static function retrieveByPK($pk, PropelPDO $con = null)
	{

		if (null !== ($obj = ApnsDeviceHistoryPeer::getInstanceFromPool((string) $pk))) {
			return $obj;
		}

		if ($con === null) {
			$con = Propel::getConnection(ApnsDeviceHistoryPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		$criteria = new Criteria(ApnsDeviceHistoryPeer::DATABASE_NAME);
		$criteria->add(ApnsDeviceHistoryPeer::PID, $pk);

		$v = ApnsDeviceHistoryPeer::doSelect($criteria, $con);

		return !empty($v) > 0 ? $v[0] : null;
	}

	/**
	 * Retrieve multiple objects by pkey.
	 *
	 * @param      array $pks List of primary keys
	 * @param      PropelPDO $con the connection to use
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function retrieveByPKs($pks, PropelPDO $con = null)
	{
		if ($con === null) {
			$con = Propel::getConnection(ApnsDeviceHistoryPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		$objs = null;
		if (empty($pks)) {
			$objs = array();
		} else {
			$criteria = new Criteria(ApnsDeviceHistoryPeer::DATABASE_NAME);
			$criteria->add(ApnsDeviceHistoryPeer::PID, $pks, Criteria::IN);
			$objs = ApnsDeviceHistoryPeer::doSelect($criteria, $con);
		}
		return $objs;
	}

	// symfony behavior
	
	/**
	 * Returns an array of arrays that contain columns in each unique index.
	 *
	 * @return array
	 */
	static public function getUniqueColumnNames()
	{
	  return array();
	}

	// symfony_behaviors behavior
	
	/**
	 * Returns the name of the hook to call from inside the supplied method.
	 *
	 * @param string $method The calling method
	 *
	 * @return string A hook name for {@link sfMixer}
	 *
	 * @throws LogicException If the method name is not recognized
	 */
	static private function getMixerPreSelectHook($method)
	{
	  if (preg_match('/^do(Select|Count)(Join(All(Except)?)?|Stmt)?/', $method, $match))
	  {
	    return sprintf('BaseApnsDeviceHistoryPeer:%s:%1$s', 'Count' == $match[1] ? 'doCount' : $match[0]);
	  }
	
	  throw new LogicException(sprintf('Unrecognized function "%s"', $method));
	}

} // BaseApnsDeviceHistoryPeer

// This is the static code needed to register the TableMap for this table with the main Propel class.
//
BaseApnsDeviceHistoryPeer::buildTableMap();

