<?php

/**
 * Base class that represents a row from the 'apns_devices' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Tue May  5 16:41:50 2015
 *
 * @package    lib.model.om
 */
abstract class BaseApnsDevice extends BaseObject  implements Persistent {


	/**
	 * The Peer class.
	 * Instance provides a convenient way of calling static methods on a class
	 * that calling code may not be able to identify.
	 * @var        ApnsDevicePeer
	 */
	protected static $peer;

	/**
	 * The value for the pid field.
	 * @var        int
	 */
	protected $pid;

	/**
	 * The value for the clientid field.
	 * @var        string
	 */
	protected $clientid;

	/**
	 * The value for the appname field.
	 * @var        string
	 */
	protected $appname;

	/**
	 * The value for the appversion field.
	 * @var        string
	 */
	protected $appversion;

	/**
	 * The value for the deviceuid field.
	 * @var        string
	 */
	protected $deviceuid;

	/**
	 * The value for the devicetoken field.
	 * @var        string
	 */
	protected $devicetoken;

	/**
	 * The value for the devicename field.
	 * @var        string
	 */
	protected $devicename;

	/**
	 * The value for the devicemodel field.
	 * @var        string
	 */
	protected $devicemodel;

	/**
	 * The value for the deviceversion field.
	 * @var        string
	 */
	protected $deviceversion;

	/**
	 * The value for the pushbadge field.
	 * Note: this column has a database default value of: 'disabled'
	 * @var        string
	 */
	protected $pushbadge;

	/**
	 * The value for the pushalert field.
	 * Note: this column has a database default value of: 'enabled'
	 * @var        string
	 */
	protected $pushalert;

	/**
	 * The value for the pushsound field.
	 * Note: this column has a database default value of: 'disabled'
	 * @var        string
	 */
	protected $pushsound;

	/**
	 * The value for the development field.
	 * Note: this column has a database default value of: 'production'
	 * @var        string
	 */
	protected $development;

	/**
	 * The value for the status field.
	 * Note: this column has a database default value of: 'active'
	 * @var        string
	 */
	protected $status;

	/**
	 * The value for the created field.
	 * @var        string
	 */
	protected $created;

	/**
	 * The value for the modified field.
	 * @var        string
	 */
	protected $modified;

	/**
	 * Flag to prevent endless save loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInSave = false;

	/**
	 * Flag to prevent endless validation loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInValidation = false;

	// symfony behavior
	
	const PEER = 'ApnsDevicePeer';

	/**
	 * Applies default values to this object.
	 * This method should be called from the object's constructor (or
	 * equivalent initialization method).
	 * @see        __construct()
	 */
	public function applyDefaultValues()
	{
		$this->pushbadge = 'disabled';
		$this->pushalert = 'enabled';
		$this->pushsound = 'disabled';
		$this->development = 'production';
		$this->status = 'active';
	}

	/**
	 * Initializes internal state of BaseApnsDevice object.
	 * @see        applyDefaults()
	 */
	public function __construct()
	{
		parent::__construct();
		$this->applyDefaultValues();
	}

	/**
	 * Get the [pid] column value.
	 * 
	 * @return     int
	 */
	public function getPid()
	{
		return $this->pid;
	}

	/**
	 * Get the [clientid] column value.
	 * 
	 * @return     string
	 */
	public function getClientid()
	{
		return $this->clientid;
	}

	/**
	 * Get the [appname] column value.
	 * 
	 * @return     string
	 */
	public function getAppname()
	{
		return $this->appname;
	}

	/**
	 * Get the [appversion] column value.
	 * 
	 * @return     string
	 */
	public function getAppversion()
	{
		return $this->appversion;
	}

	/**
	 * Get the [deviceuid] column value.
	 * 
	 * @return     string
	 */
	public function getDeviceuid()
	{
		return $this->deviceuid;
	}

	/**
	 * Get the [devicetoken] column value.
	 * 
	 * @return     string
	 */
	public function getDevicetoken()
	{
		return $this->devicetoken;
	}

	/**
	 * Get the [devicename] column value.
	 * 
	 * @return     string
	 */
	public function getDevicename()
	{
		return $this->devicename;
	}

	/**
	 * Get the [devicemodel] column value.
	 * 
	 * @return     string
	 */
	public function getDevicemodel()
	{
		return $this->devicemodel;
	}

	/**
	 * Get the [deviceversion] column value.
	 * 
	 * @return     string
	 */
	public function getDeviceversion()
	{
		return $this->deviceversion;
	}

	/**
	 * Get the [pushbadge] column value.
	 * 
	 * @return     string
	 */
	public function getPushbadge()
	{
		return $this->pushbadge;
	}

	/**
	 * Get the [pushalert] column value.
	 * 
	 * @return     string
	 */
	public function getPushalert()
	{
		return $this->pushalert;
	}

	/**
	 * Get the [pushsound] column value.
	 * 
	 * @return     string
	 */
	public function getPushsound()
	{
		return $this->pushsound;
	}

	/**
	 * Get the [development] column value.
	 * 
	 * @return     string
	 */
	public function getDevelopment()
	{
		return $this->development;
	}

	/**
	 * Get the [status] column value.
	 * 
	 * @return     string
	 */
	public function getStatus()
	{
		return $this->status;
	}

	/**
	 * Get the [optionally formatted] temporal [created] column value.
	 * 
	 *
	 * @param      string $format The date/time format string (either date()-style or strftime()-style).
	 *							If format is NULL, then the raw DateTime object will be returned.
	 * @return     mixed Formatted date/time value as string or DateTime object (if format is NULL), NULL if column is NULL, and 0 if column value is 0000-00-00 00:00:00
	 * @throws     PropelException - if unable to parse/validate the date/time value.
	 */
	public function getCreated($format = 'Y-m-d H:i:s')
	{
		if ($this->created === null) {
			return null;
		}


		if ($this->created === '0000-00-00 00:00:00') {
			// while technically this is not a default value of NULL,
			// this seems to be closest in meaning.
			return null;
		} else {
			try {
				$dt = new DateTime($this->created);
			} catch (Exception $x) {
				throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->created, true), $x);
			}
		}

		if ($format === null) {
			// Because propel.useDateTimeClass is TRUE, we return a DateTime object.
			return $dt;
		} elseif (strpos($format, '%') !== false) {
			return strftime($format, $dt->format('U'));
		} else {
			return $dt->format($format);
		}
	}

	/**
	 * Get the [optionally formatted] temporal [modified] column value.
	 * 
	 *
	 * @param      string $format The date/time format string (either date()-style or strftime()-style).
	 *							If format is NULL, then the raw DateTime object will be returned.
	 * @return     mixed Formatted date/time value as string or DateTime object (if format is NULL), NULL if column is NULL, and 0 if column value is 0000-00-00 00:00:00
	 * @throws     PropelException - if unable to parse/validate the date/time value.
	 */
	public function getModified($format = 'Y-m-d H:i:s')
	{
		if ($this->modified === null) {
			return null;
		}


		if ($this->modified === '0000-00-00 00:00:00') {
			// while technically this is not a default value of NULL,
			// this seems to be closest in meaning.
			return null;
		} else {
			try {
				$dt = new DateTime($this->modified);
			} catch (Exception $x) {
				throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->modified, true), $x);
			}
		}

		if ($format === null) {
			// Because propel.useDateTimeClass is TRUE, we return a DateTime object.
			return $dt;
		} elseif (strpos($format, '%') !== false) {
			return strftime($format, $dt->format('U'));
		} else {
			return $dt->format($format);
		}
	}

	/**
	 * Set the value of [pid] column.
	 * 
	 * @param      int $v new value
	 * @return     ApnsDevice The current object (for fluent API support)
	 */
	public function setPid($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->pid !== $v) {
			$this->pid = $v;
			$this->modifiedColumns[] = ApnsDevicePeer::PID;
		}

		return $this;
	} // setPid()

	/**
	 * Set the value of [clientid] column.
	 * 
	 * @param      string $v new value
	 * @return     ApnsDevice The current object (for fluent API support)
	 */
	public function setClientid($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->clientid !== $v) {
			$this->clientid = $v;
			$this->modifiedColumns[] = ApnsDevicePeer::CLIENTID;
		}

		return $this;
	} // setClientid()

	/**
	 * Set the value of [appname] column.
	 * 
	 * @param      string $v new value
	 * @return     ApnsDevice The current object (for fluent API support)
	 */
	public function setAppname($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->appname !== $v) {
			$this->appname = $v;
			$this->modifiedColumns[] = ApnsDevicePeer::APPNAME;
		}

		return $this;
	} // setAppname()

	/**
	 * Set the value of [appversion] column.
	 * 
	 * @param      string $v new value
	 * @return     ApnsDevice The current object (for fluent API support)
	 */
	public function setAppversion($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->appversion !== $v) {
			$this->appversion = $v;
			$this->modifiedColumns[] = ApnsDevicePeer::APPVERSION;
		}

		return $this;
	} // setAppversion()

	/**
	 * Set the value of [deviceuid] column.
	 * 
	 * @param      string $v new value
	 * @return     ApnsDevice The current object (for fluent API support)
	 */
	public function setDeviceuid($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->deviceuid !== $v) {
			$this->deviceuid = $v;
			$this->modifiedColumns[] = ApnsDevicePeer::DEVICEUID;
		}

		return $this;
	} // setDeviceuid()

	/**
	 * Set the value of [devicetoken] column.
	 * 
	 * @param      string $v new value
	 * @return     ApnsDevice The current object (for fluent API support)
	 */
	public function setDevicetoken($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->devicetoken !== $v) {
			$this->devicetoken = $v;
			$this->modifiedColumns[] = ApnsDevicePeer::DEVICETOKEN;
		}

		return $this;
	} // setDevicetoken()

	/**
	 * Set the value of [devicename] column.
	 * 
	 * @param      string $v new value
	 * @return     ApnsDevice The current object (for fluent API support)
	 */
	public function setDevicename($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->devicename !== $v) {
			$this->devicename = $v;
			$this->modifiedColumns[] = ApnsDevicePeer::DEVICENAME;
		}

		return $this;
	} // setDevicename()

	/**
	 * Set the value of [devicemodel] column.
	 * 
	 * @param      string $v new value
	 * @return     ApnsDevice The current object (for fluent API support)
	 */
	public function setDevicemodel($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->devicemodel !== $v) {
			$this->devicemodel = $v;
			$this->modifiedColumns[] = ApnsDevicePeer::DEVICEMODEL;
		}

		return $this;
	} // setDevicemodel()

	/**
	 * Set the value of [deviceversion] column.
	 * 
	 * @param      string $v new value
	 * @return     ApnsDevice The current object (for fluent API support)
	 */
	public function setDeviceversion($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->deviceversion !== $v) {
			$this->deviceversion = $v;
			$this->modifiedColumns[] = ApnsDevicePeer::DEVICEVERSION;
		}

		return $this;
	} // setDeviceversion()

	/**
	 * Set the value of [pushbadge] column.
	 * 
	 * @param      string $v new value
	 * @return     ApnsDevice The current object (for fluent API support)
	 */
	public function setPushbadge($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->pushbadge !== $v || $this->isNew()) {
			$this->pushbadge = $v;
			$this->modifiedColumns[] = ApnsDevicePeer::PUSHBADGE;
		}

		return $this;
	} // setPushbadge()

	/**
	 * Set the value of [pushalert] column.
	 * 
	 * @param      string $v new value
	 * @return     ApnsDevice The current object (for fluent API support)
	 */
	public function setPushalert($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->pushalert !== $v || $this->isNew()) {
			$this->pushalert = $v;
			$this->modifiedColumns[] = ApnsDevicePeer::PUSHALERT;
		}

		return $this;
	} // setPushalert()

	/**
	 * Set the value of [pushsound] column.
	 * 
	 * @param      string $v new value
	 * @return     ApnsDevice The current object (for fluent API support)
	 */
	public function setPushsound($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->pushsound !== $v || $this->isNew()) {
			$this->pushsound = $v;
			$this->modifiedColumns[] = ApnsDevicePeer::PUSHSOUND;
		}

		return $this;
	} // setPushsound()

	/**
	 * Set the value of [development] column.
	 * 
	 * @param      string $v new value
	 * @return     ApnsDevice The current object (for fluent API support)
	 */
	public function setDevelopment($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->development !== $v || $this->isNew()) {
			$this->development = $v;
			$this->modifiedColumns[] = ApnsDevicePeer::DEVELOPMENT;
		}

		return $this;
	} // setDevelopment()

	/**
	 * Set the value of [status] column.
	 * 
	 * @param      string $v new value
	 * @return     ApnsDevice The current object (for fluent API support)
	 */
	public function setStatus($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->status !== $v || $this->isNew()) {
			$this->status = $v;
			$this->modifiedColumns[] = ApnsDevicePeer::STATUS;
		}

		return $this;
	} // setStatus()

	/**
	 * Sets the value of [created] column to a normalized version of the date/time value specified.
	 * 
	 * @param      mixed $v string, integer (timestamp), or DateTime value.  Empty string will
	 *						be treated as NULL for temporal objects.
	 * @return     ApnsDevice The current object (for fluent API support)
	 */
	public function setCreated($v)
	{
		// we treat '' as NULL for temporal objects because DateTime('') == DateTime('now')
		// -- which is unexpected, to say the least.
		if ($v === null || $v === '') {
			$dt = null;
		} elseif ($v instanceof DateTime) {
			$dt = $v;
		} else {
			// some string/numeric value passed; we normalize that so that we can
			// validate it.
			try {
				if (is_numeric($v)) { // if it's a unix timestamp
					$dt = new DateTime('@'.$v, new DateTimeZone('UTC'));
					// We have to explicitly specify and then change the time zone because of a
					// DateTime bug: http://bugs.php.net/bug.php?id=43003
					$dt->setTimeZone(new DateTimeZone(date_default_timezone_get()));
				} else {
					$dt = new DateTime($v);
				}
			} catch (Exception $x) {
				throw new PropelException('Error parsing date/time value: ' . var_export($v, true), $x);
			}
		}

		if ( $this->created !== null || $dt !== null ) {
			// (nested ifs are a little easier to read in this case)

			$currNorm = ($this->created !== null && $tmpDt = new DateTime($this->created)) ? $tmpDt->format('Y-m-d H:i:s') : null;
			$newNorm = ($dt !== null) ? $dt->format('Y-m-d H:i:s') : null;

			if ( ($currNorm !== $newNorm) // normalized values don't match 
					)
			{
				$this->created = ($dt ? $dt->format('Y-m-d H:i:s') : null);
				$this->modifiedColumns[] = ApnsDevicePeer::CREATED;
			}
		} // if either are not null

		return $this;
	} // setCreated()

	/**
	 * Sets the value of [modified] column to a normalized version of the date/time value specified.
	 * 
	 * @param      mixed $v string, integer (timestamp), or DateTime value.  Empty string will
	 *						be treated as NULL for temporal objects.
	 * @return     ApnsDevice The current object (for fluent API support)
	 */
	public function setModified($v)
	{
		// we treat '' as NULL for temporal objects because DateTime('') == DateTime('now')
		// -- which is unexpected, to say the least.
		if ($v === null || $v === '') {
			$dt = null;
		} elseif ($v instanceof DateTime) {
			$dt = $v;
		} else {
			// some string/numeric value passed; we normalize that so that we can
			// validate it.
			try {
				if (is_numeric($v)) { // if it's a unix timestamp
					$dt = new DateTime('@'.$v, new DateTimeZone('UTC'));
					// We have to explicitly specify and then change the time zone because of a
					// DateTime bug: http://bugs.php.net/bug.php?id=43003
					$dt->setTimeZone(new DateTimeZone(date_default_timezone_get()));
				} else {
					$dt = new DateTime($v);
				}
			} catch (Exception $x) {
				throw new PropelException('Error parsing date/time value: ' . var_export($v, true), $x);
			}
		}

		if ( $this->modified !== null || $dt !== null ) {
			// (nested ifs are a little easier to read in this case)

			$currNorm = ($this->modified !== null && $tmpDt = new DateTime($this->modified)) ? $tmpDt->format('Y-m-d H:i:s') : null;
			$newNorm = ($dt !== null) ? $dt->format('Y-m-d H:i:s') : null;

			if ( ($currNorm !== $newNorm) // normalized values don't match 
					)
			{
				$this->modified = ($dt ? $dt->format('Y-m-d H:i:s') : null);
				$this->modifiedColumns[] = ApnsDevicePeer::MODIFIED;
			}
		} // if either are not null

		return $this;
	} // setModified()

	/**
	 * Indicates whether the columns in this object are only set to default values.
	 *
	 * This method can be used in conjunction with isModified() to indicate whether an object is both
	 * modified _and_ has some values set which are non-default.
	 *
	 * @return     boolean Whether the columns in this object are only been set with default values.
	 */
	public function hasOnlyDefaultValues()
	{
			if ($this->pushbadge !== 'disabled') {
				return false;
			}

			if ($this->pushalert !== 'enabled') {
				return false;
			}

			if ($this->pushsound !== 'disabled') {
				return false;
			}

			if ($this->development !== 'production') {
				return false;
			}

			if ($this->status !== 'active') {
				return false;
			}

		// otherwise, everything was equal, so return TRUE
		return true;
	} // hasOnlyDefaultValues()

	/**
	 * Hydrates (populates) the object variables with values from the database resultset.
	 *
	 * An offset (0-based "start column") is specified so that objects can be hydrated
	 * with a subset of the columns in the resultset rows.  This is needed, for example,
	 * for results of JOIN queries where the resultset row includes columns from two or
	 * more tables.
	 *
	 * @param      array $row The row returned by PDOStatement->fetch(PDO::FETCH_NUM)
	 * @param      int $startcol 0-based offset column which indicates which restultset column to start with.
	 * @param      boolean $rehydrate Whether this object is being re-hydrated from the database.
	 * @return     int next starting column
	 * @throws     PropelException  - Any caught Exception will be rewrapped as a PropelException.
	 */
	public function hydrate($row, $startcol = 0, $rehydrate = false)
	{
		try {

			$this->pid = ($row[$startcol + 0] !== null) ? (int) $row[$startcol + 0] : null;
			$this->clientid = ($row[$startcol + 1] !== null) ? (string) $row[$startcol + 1] : null;
			$this->appname = ($row[$startcol + 2] !== null) ? (string) $row[$startcol + 2] : null;
			$this->appversion = ($row[$startcol + 3] !== null) ? (string) $row[$startcol + 3] : null;
			$this->deviceuid = ($row[$startcol + 4] !== null) ? (string) $row[$startcol + 4] : null;
			$this->devicetoken = ($row[$startcol + 5] !== null) ? (string) $row[$startcol + 5] : null;
			$this->devicename = ($row[$startcol + 6] !== null) ? (string) $row[$startcol + 6] : null;
			$this->devicemodel = ($row[$startcol + 7] !== null) ? (string) $row[$startcol + 7] : null;
			$this->deviceversion = ($row[$startcol + 8] !== null) ? (string) $row[$startcol + 8] : null;
			$this->pushbadge = ($row[$startcol + 9] !== null) ? (string) $row[$startcol + 9] : null;
			$this->pushalert = ($row[$startcol + 10] !== null) ? (string) $row[$startcol + 10] : null;
			$this->pushsound = ($row[$startcol + 11] !== null) ? (string) $row[$startcol + 11] : null;
			$this->development = ($row[$startcol + 12] !== null) ? (string) $row[$startcol + 12] : null;
			$this->status = ($row[$startcol + 13] !== null) ? (string) $row[$startcol + 13] : null;
			$this->created = ($row[$startcol + 14] !== null) ? (string) $row[$startcol + 14] : null;
			$this->modified = ($row[$startcol + 15] !== null) ? (string) $row[$startcol + 15] : null;
			$this->resetModified();

			$this->setNew(false);

			if ($rehydrate) {
				$this->ensureConsistency();
			}

			// FIXME - using NUM_COLUMNS may be clearer.
			return $startcol + 16; // 16 = ApnsDevicePeer::NUM_COLUMNS - ApnsDevicePeer::NUM_LAZY_LOAD_COLUMNS).

		} catch (Exception $e) {
			throw new PropelException("Error populating ApnsDevice object", $e);
		}
	}

	/**
	 * Checks and repairs the internal consistency of the object.
	 *
	 * This method is executed after an already-instantiated object is re-hydrated
	 * from the database.  It exists to check any foreign keys to make sure that
	 * the objects related to the current object are correct based on foreign key.
	 *
	 * You can override this method in the stub class, but you should always invoke
	 * the base method from the overridden method (i.e. parent::ensureConsistency()),
	 * in case your model changes.
	 *
	 * @throws     PropelException
	 */
	public function ensureConsistency()
	{

	} // ensureConsistency

	/**
	 * Reloads this object from datastore based on primary key and (optionally) resets all associated objects.
	 *
	 * This will only work if the object has been saved and has a valid primary key set.
	 *
	 * @param      boolean $deep (optional) Whether to also de-associated any related objects.
	 * @param      PropelPDO $con (optional) The PropelPDO connection to use.
	 * @return     void
	 * @throws     PropelException - if this object is deleted, unsaved or doesn't have pk match in db
	 */
	public function reload($deep = false, PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("Cannot reload a deleted object.");
		}

		if ($this->isNew()) {
			throw new PropelException("Cannot reload an unsaved object.");
		}

		if ($con === null) {
			$con = Propel::getConnection(ApnsDevicePeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		// We don't need to alter the object instance pool; we're just modifying this instance
		// already in the pool.

		$stmt = ApnsDevicePeer::doSelectStmt($this->buildPkeyCriteria(), $con);
		$row = $stmt->fetch(PDO::FETCH_NUM);
		$stmt->closeCursor();
		if (!$row) {
			throw new PropelException('Cannot find matching row in the database to reload object values.');
		}
		$this->hydrate($row, 0, true); // rehydrate

		if ($deep) {  // also de-associate any related objects?

		} // if (deep)
	}

	/**
	 * Removes this object from datastore and sets delete attribute.
	 *
	 * @param      PropelPDO $con
	 * @return     void
	 * @throws     PropelException
	 * @see        BaseObject::setDeleted()
	 * @see        BaseObject::isDeleted()
	 */
	public function delete(PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("This object has already been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(ApnsDevicePeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		try {
			$ret = $this->preDelete($con);
			// symfony_behaviors behavior
			foreach (sfMixer::getCallables('BaseApnsDevice:delete:pre') as $callable)
			{
			  if (call_user_func($callable, $this, $con))
			  {
			    $con->commit();
			
			    return;
			  }
			}

			if ($ret) {
				ApnsDevicePeer::doDelete($this, $con);
				$this->postDelete($con);
				// symfony_behaviors behavior
				foreach (sfMixer::getCallables('BaseApnsDevice:delete:post') as $callable)
				{
				  call_user_func($callable, $this, $con);
				}

				$this->setDeleted(true);
				$con->commit();
			} else {
				$con->commit();
			}
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Persists this object to the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All modified related objects will also be persisted in the doSave()
	 * method.  This method wraps all precipitate database operations in a
	 * single transaction.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        doSave()
	 */
	public function save(PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("You cannot save an object that has been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(ApnsDevicePeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		$isInsert = $this->isNew();
		try {
			$ret = $this->preSave($con);
			// symfony_behaviors behavior
			foreach (sfMixer::getCallables('BaseApnsDevice:save:pre') as $callable)
			{
			  if (is_integer($affectedRows = call_user_func($callable, $this, $con)))
			  {
			    $con->commit();
			
			    return $affectedRows;
			  }
			}

			if ($isInsert) {
				$ret = $ret && $this->preInsert($con);
			} else {
				$ret = $ret && $this->preUpdate($con);
			}
			if ($ret) {
				$affectedRows = $this->doSave($con);
				if ($isInsert) {
					$this->postInsert($con);
				} else {
					$this->postUpdate($con);
				}
				$this->postSave($con);
				// symfony_behaviors behavior
				foreach (sfMixer::getCallables('BaseApnsDevice:save:post') as $callable)
				{
				  call_user_func($callable, $this, $con, $affectedRows);
				}

				ApnsDevicePeer::addInstanceToPool($this);
			} else {
				$affectedRows = 0;
			}
			$con->commit();
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Performs the work of inserting or updating the row in the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All related objects are also updated in this method.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        save()
	 */
	protected function doSave(PropelPDO $con)
	{
		$affectedRows = 0; // initialize var to track total num of affected rows
		if (!$this->alreadyInSave) {
			$this->alreadyInSave = true;

			if ($this->isNew() ) {
				$this->modifiedColumns[] = ApnsDevicePeer::PID;
			}

			// If this object has been modified, then save it to the database.
			if ($this->isModified()) {
				if ($this->isNew()) {
					$pk = ApnsDevicePeer::doInsert($this, $con);
					$affectedRows += 1; // we are assuming that there is only 1 row per doInsert() which
										 // should always be true here (even though technically
										 // BasePeer::doInsert() can insert multiple rows).

					$this->setPid($pk);  //[IMV] update autoincrement primary key

					$this->setNew(false);
				} else {
					$affectedRows += ApnsDevicePeer::doUpdate($this, $con);
				}

				$this->resetModified(); // [HL] After being saved an object is no longer 'modified'
			}

			$this->alreadyInSave = false;

		}
		return $affectedRows;
	} // doSave()

	/**
	 * Array of ValidationFailed objects.
	 * @var        array ValidationFailed[]
	 */
	protected $validationFailures = array();

	/**
	 * Gets any ValidationFailed objects that resulted from last call to validate().
	 *
	 *
	 * @return     array ValidationFailed[]
	 * @see        validate()
	 */
	public function getValidationFailures()
	{
		return $this->validationFailures;
	}

	/**
	 * Validates the objects modified field values and all objects related to this table.
	 *
	 * If $columns is either a column name or an array of column names
	 * only those columns are validated.
	 *
	 * @param      mixed $columns Column name or an array of column names.
	 * @return     boolean Whether all columns pass validation.
	 * @see        doValidate()
	 * @see        getValidationFailures()
	 */
	public function validate($columns = null)
	{
		$res = $this->doValidate($columns);
		if ($res === true) {
			$this->validationFailures = array();
			return true;
		} else {
			$this->validationFailures = $res;
			return false;
		}
	}

	/**
	 * This function performs the validation work for complex object models.
	 *
	 * In addition to checking the current object, all related objects will
	 * also be validated.  If all pass then <code>true</code> is returned; otherwise
	 * an aggreagated array of ValidationFailed objects will be returned.
	 *
	 * @param      array $columns Array of column names to validate.
	 * @return     mixed <code>true</code> if all validations pass; array of <code>ValidationFailed</code> objets otherwise.
	 */
	protected function doValidate($columns = null)
	{
		if (!$this->alreadyInValidation) {
			$this->alreadyInValidation = true;
			$retval = null;

			$failureMap = array();


			if (($retval = ApnsDevicePeer::doValidate($this, $columns)) !== true) {
				$failureMap = array_merge($failureMap, $retval);
			}



			$this->alreadyInValidation = false;
		}

		return (!empty($failureMap) ? $failureMap : true);
	}

	/**
	 * Retrieves a field from the object by name passed in as a string.
	 *
	 * @param      string $name name
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     mixed Value of field.
	 */
	public function getByName($name, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = ApnsDevicePeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		$field = $this->getByPosition($pos);
		return $field;
	}

	/**
	 * Retrieves a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @return     mixed Value of field at $pos
	 */
	public function getByPosition($pos)
	{
		switch($pos) {
			case 0:
				return $this->getPid();
				break;
			case 1:
				return $this->getClientid();
				break;
			case 2:
				return $this->getAppname();
				break;
			case 3:
				return $this->getAppversion();
				break;
			case 4:
				return $this->getDeviceuid();
				break;
			case 5:
				return $this->getDevicetoken();
				break;
			case 6:
				return $this->getDevicename();
				break;
			case 7:
				return $this->getDevicemodel();
				break;
			case 8:
				return $this->getDeviceversion();
				break;
			case 9:
				return $this->getPushbadge();
				break;
			case 10:
				return $this->getPushalert();
				break;
			case 11:
				return $this->getPushsound();
				break;
			case 12:
				return $this->getDevelopment();
				break;
			case 13:
				return $this->getStatus();
				break;
			case 14:
				return $this->getCreated();
				break;
			case 15:
				return $this->getModified();
				break;
			default:
				return null;
				break;
		} // switch()
	}

	/**
	 * Exports the object as an array.
	 *
	 * You can specify the key type of the array by passing one of the class
	 * type constants.
	 *
	 * @param      string $keyType (optional) One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                        BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM. Defaults to BasePeer::TYPE_PHPNAME.
	 * @param      boolean $includeLazyLoadColumns (optional) Whether to include lazy loaded columns.  Defaults to TRUE.
	 * @return     an associative array containing the field names (as keys) and field values
	 */
	public function toArray($keyType = BasePeer::TYPE_PHPNAME, $includeLazyLoadColumns = true)
	{
		$keys = ApnsDevicePeer::getFieldNames($keyType);
		$result = array(
			$keys[0] => $this->getPid(),
			$keys[1] => $this->getClientid(),
			$keys[2] => $this->getAppname(),
			$keys[3] => $this->getAppversion(),
			$keys[4] => $this->getDeviceuid(),
			$keys[5] => $this->getDevicetoken(),
			$keys[6] => $this->getDevicename(),
			$keys[7] => $this->getDevicemodel(),
			$keys[8] => $this->getDeviceversion(),
			$keys[9] => $this->getPushbadge(),
			$keys[10] => $this->getPushalert(),
			$keys[11] => $this->getPushsound(),
			$keys[12] => $this->getDevelopment(),
			$keys[13] => $this->getStatus(),
			$keys[14] => $this->getCreated(),
			$keys[15] => $this->getModified(),
		);
		return $result;
	}

	/**
	 * Sets a field from the object by name passed in as a string.
	 *
	 * @param      string $name peer name
	 * @param      mixed $value field value
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     void
	 */
	public function setByName($name, $value, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = ApnsDevicePeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		return $this->setByPosition($pos, $value);
	}

	/**
	 * Sets a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @param      mixed $value field value
	 * @return     void
	 */
	public function setByPosition($pos, $value)
	{
		switch($pos) {
			case 0:
				$this->setPid($value);
				break;
			case 1:
				$this->setClientid($value);
				break;
			case 2:
				$this->setAppname($value);
				break;
			case 3:
				$this->setAppversion($value);
				break;
			case 4:
				$this->setDeviceuid($value);
				break;
			case 5:
				$this->setDevicetoken($value);
				break;
			case 6:
				$this->setDevicename($value);
				break;
			case 7:
				$this->setDevicemodel($value);
				break;
			case 8:
				$this->setDeviceversion($value);
				break;
			case 9:
				$this->setPushbadge($value);
				break;
			case 10:
				$this->setPushalert($value);
				break;
			case 11:
				$this->setPushsound($value);
				break;
			case 12:
				$this->setDevelopment($value);
				break;
			case 13:
				$this->setStatus($value);
				break;
			case 14:
				$this->setCreated($value);
				break;
			case 15:
				$this->setModified($value);
				break;
		} // switch()
	}

	/**
	 * Populates the object using an array.
	 *
	 * This is particularly useful when populating an object from one of the
	 * request arrays (e.g. $_POST).  This method goes through the column
	 * names, checking to see whether a matching key exists in populated
	 * array. If so the setByName() method is called for that column.
	 *
	 * You can specify the key type of the array by additionally passing one
	 * of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME,
	 * BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM.
	 * The default key type is the column's phpname (e.g. 'AuthorId')
	 *
	 * @param      array  $arr     An array to populate the object from.
	 * @param      string $keyType The type of keys the array uses.
	 * @return     void
	 */
	public function fromArray($arr, $keyType = BasePeer::TYPE_PHPNAME)
	{
		$keys = ApnsDevicePeer::getFieldNames($keyType);

		if (array_key_exists($keys[0], $arr)) $this->setPid($arr[$keys[0]]);
		if (array_key_exists($keys[1], $arr)) $this->setClientid($arr[$keys[1]]);
		if (array_key_exists($keys[2], $arr)) $this->setAppname($arr[$keys[2]]);
		if (array_key_exists($keys[3], $arr)) $this->setAppversion($arr[$keys[3]]);
		if (array_key_exists($keys[4], $arr)) $this->setDeviceuid($arr[$keys[4]]);
		if (array_key_exists($keys[5], $arr)) $this->setDevicetoken($arr[$keys[5]]);
		if (array_key_exists($keys[6], $arr)) $this->setDevicename($arr[$keys[6]]);
		if (array_key_exists($keys[7], $arr)) $this->setDevicemodel($arr[$keys[7]]);
		if (array_key_exists($keys[8], $arr)) $this->setDeviceversion($arr[$keys[8]]);
		if (array_key_exists($keys[9], $arr)) $this->setPushbadge($arr[$keys[9]]);
		if (array_key_exists($keys[10], $arr)) $this->setPushalert($arr[$keys[10]]);
		if (array_key_exists($keys[11], $arr)) $this->setPushsound($arr[$keys[11]]);
		if (array_key_exists($keys[12], $arr)) $this->setDevelopment($arr[$keys[12]]);
		if (array_key_exists($keys[13], $arr)) $this->setStatus($arr[$keys[13]]);
		if (array_key_exists($keys[14], $arr)) $this->setCreated($arr[$keys[14]]);
		if (array_key_exists($keys[15], $arr)) $this->setModified($arr[$keys[15]]);
	}

	/**
	 * Build a Criteria object containing the values of all modified columns in this object.
	 *
	 * @return     Criteria The Criteria object containing all modified values.
	 */
	public function buildCriteria()
	{
		$criteria = new Criteria(ApnsDevicePeer::DATABASE_NAME);

		if ($this->isColumnModified(ApnsDevicePeer::PID)) $criteria->add(ApnsDevicePeer::PID, $this->pid);
		if ($this->isColumnModified(ApnsDevicePeer::CLIENTID)) $criteria->add(ApnsDevicePeer::CLIENTID, $this->clientid);
		if ($this->isColumnModified(ApnsDevicePeer::APPNAME)) $criteria->add(ApnsDevicePeer::APPNAME, $this->appname);
		if ($this->isColumnModified(ApnsDevicePeer::APPVERSION)) $criteria->add(ApnsDevicePeer::APPVERSION, $this->appversion);
		if ($this->isColumnModified(ApnsDevicePeer::DEVICEUID)) $criteria->add(ApnsDevicePeer::DEVICEUID, $this->deviceuid);
		if ($this->isColumnModified(ApnsDevicePeer::DEVICETOKEN)) $criteria->add(ApnsDevicePeer::DEVICETOKEN, $this->devicetoken);
		if ($this->isColumnModified(ApnsDevicePeer::DEVICENAME)) $criteria->add(ApnsDevicePeer::DEVICENAME, $this->devicename);
		if ($this->isColumnModified(ApnsDevicePeer::DEVICEMODEL)) $criteria->add(ApnsDevicePeer::DEVICEMODEL, $this->devicemodel);
		if ($this->isColumnModified(ApnsDevicePeer::DEVICEVERSION)) $criteria->add(ApnsDevicePeer::DEVICEVERSION, $this->deviceversion);
		if ($this->isColumnModified(ApnsDevicePeer::PUSHBADGE)) $criteria->add(ApnsDevicePeer::PUSHBADGE, $this->pushbadge);
		if ($this->isColumnModified(ApnsDevicePeer::PUSHALERT)) $criteria->add(ApnsDevicePeer::PUSHALERT, $this->pushalert);
		if ($this->isColumnModified(ApnsDevicePeer::PUSHSOUND)) $criteria->add(ApnsDevicePeer::PUSHSOUND, $this->pushsound);
		if ($this->isColumnModified(ApnsDevicePeer::DEVELOPMENT)) $criteria->add(ApnsDevicePeer::DEVELOPMENT, $this->development);
		if ($this->isColumnModified(ApnsDevicePeer::STATUS)) $criteria->add(ApnsDevicePeer::STATUS, $this->status);
		if ($this->isColumnModified(ApnsDevicePeer::CREATED)) $criteria->add(ApnsDevicePeer::CREATED, $this->created);
		if ($this->isColumnModified(ApnsDevicePeer::MODIFIED)) $criteria->add(ApnsDevicePeer::MODIFIED, $this->modified);

		return $criteria;
	}

	/**
	 * Builds a Criteria object containing the primary key for this object.
	 *
	 * Unlike buildCriteria() this method includes the primary key values regardless
	 * of whether or not they have been modified.
	 *
	 * @return     Criteria The Criteria object containing value(s) for primary key(s).
	 */
	public function buildPkeyCriteria()
	{
		$criteria = new Criteria(ApnsDevicePeer::DATABASE_NAME);

		$criteria->add(ApnsDevicePeer::PID, $this->pid);

		return $criteria;
	}

	/**
	 * Returns the primary key for this object (row).
	 * @return     int
	 */
	public function getPrimaryKey()
	{
		return $this->getPid();
	}

	/**
	 * Generic method to set the primary key (pid column).
	 *
	 * @param      int $key Primary key.
	 * @return     void
	 */
	public function setPrimaryKey($key)
	{
		$this->setPid($key);
	}

	/**
	 * Sets contents of passed object to values from current object.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      object $copyObj An object of ApnsDevice (or compatible) type.
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @throws     PropelException
	 */
	public function copyInto($copyObj, $deepCopy = false)
	{

		$copyObj->setClientid($this->clientid);

		$copyObj->setAppname($this->appname);

		$copyObj->setAppversion($this->appversion);

		$copyObj->setDeviceuid($this->deviceuid);

		$copyObj->setDevicetoken($this->devicetoken);

		$copyObj->setDevicename($this->devicename);

		$copyObj->setDevicemodel($this->devicemodel);

		$copyObj->setDeviceversion($this->deviceversion);

		$copyObj->setPushbadge($this->pushbadge);

		$copyObj->setPushalert($this->pushalert);

		$copyObj->setPushsound($this->pushsound);

		$copyObj->setDevelopment($this->development);

		$copyObj->setStatus($this->status);

		$copyObj->setCreated($this->created);

		$copyObj->setModified($this->modified);


		$copyObj->setNew(true);

		$copyObj->setPid(NULL); // this is a auto-increment column, so set to default value

	}

	/**
	 * Makes a copy of this object that will be inserted as a new row in table when saved.
	 * It creates a new object filling in the simple attributes, but skipping any primary
	 * keys that are defined for the table.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @return     ApnsDevice Clone of current object.
	 * @throws     PropelException
	 */
	public function copy($deepCopy = false)
	{
		// we use get_class(), because this might be a subclass
		$clazz = get_class($this);
		$copyObj = new $clazz();
		$this->copyInto($copyObj, $deepCopy);
		return $copyObj;
	}

	/**
	 * Returns a peer instance associated with this om.
	 *
	 * Since Peer classes are not to have any instance attributes, this method returns the
	 * same instance for all member of this class. The method could therefore
	 * be static, but this would prevent one from overriding the behavior.
	 *
	 * @return     ApnsDevicePeer
	 */
	public function getPeer()
	{
		if (self::$peer === null) {
			self::$peer = new ApnsDevicePeer();
		}
		return self::$peer;
	}

	/**
	 * Resets all collections of referencing foreign keys.
	 *
	 * This method is a user-space workaround for PHP's inability to garbage collect objects
	 * with circular references.  This is currently necessary when using Propel in certain
	 * daemon or large-volumne/high-memory operations.
	 *
	 * @param      boolean $deep Whether to also clear the references on all associated objects.
	 */
	public function clearAllReferences($deep = false)
	{
		if ($deep) {
		} // if ($deep)

	}

	// symfony_behaviors behavior
	
	/**
	 * Calls methods defined via {@link sfMixer}.
	 */
	public function __call($method, $arguments)
	{
	  if (!$callable = sfMixer::getCallable('BaseApnsDevice:'.$method))
	  {
	    throw new sfException(sprintf('Call to undefined method BaseApnsDevice::%s', $method));
	  }
	
	  array_unshift($arguments, $this);
	
	  return call_user_func_array($callable, $arguments);
	}

} // BaseApnsDevice
