<?php

/**
 * Base class that represents a row from the 'issue' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Tue May  5 16:41:50 2015
 *
 * @package    lib.model.om
 */
abstract class BaseIssue extends BaseObject  implements Persistent {


	/**
	 * The Peer class.
	 * Instance provides a convenient way of calling static methods on a class
	 * that calling code may not be able to identify.
	 * @var        IssuePeer
	 */
	protected static $peer;

	/**
	 * The value for the id field.
	 * @var        int
	 */
	protected $id;

	/**
	 * The value for the created_at field.
	 * @var        string
	 */
	protected $created_at;

	/**
	 * The value for the updated_at field.
	 * @var        string
	 */
	protected $updated_at;

	/**
	 * The value for the publication_id field.
	 * @var        int
	 */
	protected $publication_id;

	/**
	 * The value for the name field.
	 * @var        string
	 */
	protected $name;

	/**
	 * The value for the free field.
	 * Note: this column has a database default value of: true
	 * @var        boolean
	 */
	protected $free;

	/**
	 * The value for the product_id field.
	 * @var        string
	 */
	protected $product_id;

	/**
	 * The value for the title field.
	 * @var        string
	 */
	protected $title;

	/**
	 * The value for the info field.
	 * @var        string
	 */
	protected $info;

	/**
	 * The value for the date field.
	 * @var        string
	 */
	protected $date;

	/**
	 * The value for the published field.
	 * Note: this column has a database default value of: true
	 * @var        boolean
	 */
	protected $published;

	/**
	 * The value for the cover field.
	 * @var        string
	 */
	protected $cover;

	/**
	 * The value for the url field.
	 * @var        string
	 */
	protected $url;

	/**
	 * The value for the upload_type field.
	 * Note: this column has a database default value of: 'u'
	 * @var        string
	 */
	protected $upload_type;

	/**
	 * The value for the uploaded_cover field.
	 * @var        string
	 */
	protected $uploaded_cover;

	/**
	 * The value for the uploaded_hpub field.
	 * @var        string
	 */
	protected $uploaded_hpub;

	/**
	 * The value for the uploaded_zip field.
	 * @var        string
	 */
	protected $uploaded_zip;

	/**
	 * The value for the allow_notification field.
	 * Note: this column has a database default value of: false
	 * @var        boolean
	 */
	protected $allow_notification;

	/**
	 * The value for the notified field.
	 * Note: this column has a database default value of: false
	 * @var        boolean
	 */
	protected $notified;

	/**
	 * The value for the itunes_include field.
	 * Note: this column has a database default value of: false
	 * @var        boolean
	 */
	protected $itunes_include;

	/**
	 * The value for the itunes_summary field.
	 * @var        string
	 */
	protected $itunes_summary;

	/**
	 * The value for the itunes_coverart_url field.
	 * @var        string
	 */
	protected $itunes_coverart_url;

	/**
	 * The value for the itunes_published field.
	 * @var        string
	 */
	protected $itunes_published;

	/**
	 * The value for the itunes_updated field.
	 * @var        string
	 */
	protected $itunes_updated;

	/**
	 * @var        Publication
	 */
	protected $aPublication;

	/**
	 * Flag to prevent endless save loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInSave = false;

	/**
	 * Flag to prevent endless validation loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInValidation = false;

	// symfony behavior
	
	const PEER = 'IssuePeer';

	/**
	 * Applies default values to this object.
	 * This method should be called from the object's constructor (or
	 * equivalent initialization method).
	 * @see        __construct()
	 */
	public function applyDefaultValues()
	{
		$this->free = true;
		$this->published = true;
		$this->upload_type = 'u';
		$this->allow_notification = false;
		$this->notified = false;
		$this->itunes_include = false;
	}

	/**
	 * Initializes internal state of BaseIssue object.
	 * @see        applyDefaults()
	 */
	public function __construct()
	{
		parent::__construct();
		$this->applyDefaultValues();
	}

	/**
	 * Get the [id] column value.
	 * 
	 * @return     int
	 */
	public function getId()
	{
		return $this->id;
	}

	/**
	 * Get the [optionally formatted] temporal [created_at] column value.
	 * 
	 *
	 * @param      string $format The date/time format string (either date()-style or strftime()-style).
	 *							If format is NULL, then the raw DateTime object will be returned.
	 * @return     mixed Formatted date/time value as string or DateTime object (if format is NULL), NULL if column is NULL, and 0 if column value is 0000-00-00 00:00:00
	 * @throws     PropelException - if unable to parse/validate the date/time value.
	 */
	public function getCreatedAt($format = 'Y-m-d H:i:s')
	{
		if ($this->created_at === null) {
			return null;
		}


		if ($this->created_at === '0000-00-00 00:00:00') {
			// while technically this is not a default value of NULL,
			// this seems to be closest in meaning.
			return null;
		} else {
			try {
				$dt = new DateTime($this->created_at);
			} catch (Exception $x) {
				throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->created_at, true), $x);
			}
		}

		if ($format === null) {
			// Because propel.useDateTimeClass is TRUE, we return a DateTime object.
			return $dt;
		} elseif (strpos($format, '%') !== false) {
			return strftime($format, $dt->format('U'));
		} else {
			return $dt->format($format);
		}
	}

	/**
	 * Get the [optionally formatted] temporal [updated_at] column value.
	 * 
	 *
	 * @param      string $format The date/time format string (either date()-style or strftime()-style).
	 *							If format is NULL, then the raw DateTime object will be returned.
	 * @return     mixed Formatted date/time value as string or DateTime object (if format is NULL), NULL if column is NULL, and 0 if column value is 0000-00-00 00:00:00
	 * @throws     PropelException - if unable to parse/validate the date/time value.
	 */
	public function getUpdatedAt($format = 'Y-m-d H:i:s')
	{
		if ($this->updated_at === null) {
			return null;
		}


		if ($this->updated_at === '0000-00-00 00:00:00') {
			// while technically this is not a default value of NULL,
			// this seems to be closest in meaning.
			return null;
		} else {
			try {
				$dt = new DateTime($this->updated_at);
			} catch (Exception $x) {
				throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->updated_at, true), $x);
			}
		}

		if ($format === null) {
			// Because propel.useDateTimeClass is TRUE, we return a DateTime object.
			return $dt;
		} elseif (strpos($format, '%') !== false) {
			return strftime($format, $dt->format('U'));
		} else {
			return $dt->format($format);
		}
	}

	/**
	 * Get the [publication_id] column value.
	 * 
	 * @return     int
	 */
	public function getPublicationId()
	{
		return $this->publication_id;
	}

	/**
	 * Get the [name] column value.
	 * 
	 * @return     string
	 */
	public function getName()
	{
		return $this->name;
	}

	/**
	 * Get the [free] column value.
	 * 
	 * @return     boolean
	 */
	public function getFree()
	{
		return $this->free;
	}

	/**
	 * Get the [product_id] column value.
	 * 
	 * @return     string
	 */
	public function getProductId()
	{
		return $this->product_id;
	}

	/**
	 * Get the [title] column value.
	 * 
	 * @return     string
	 */
	public function getTitle()
	{
		return $this->title;
	}

	/**
	 * Get the [info] column value.
	 * 
	 * @return     string
	 */
	public function getInfo()
	{
		return $this->info;
	}

	/**
	 * Get the [optionally formatted] temporal [date] column value.
	 * 
	 *
	 * @param      string $format The date/time format string (either date()-style or strftime()-style).
	 *							If format is NULL, then the raw DateTime object will be returned.
	 * @return     mixed Formatted date/time value as string or DateTime object (if format is NULL), NULL if column is NULL, and 0 if column value is 0000-00-00
	 * @throws     PropelException - if unable to parse/validate the date/time value.
	 */
	public function getDate($format = 'Y-m-d')
	{
		if ($this->date === null) {
			return null;
		}


		if ($this->date === '0000-00-00') {
			// while technically this is not a default value of NULL,
			// this seems to be closest in meaning.
			return null;
		} else {
			try {
				$dt = new DateTime($this->date);
			} catch (Exception $x) {
				throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->date, true), $x);
			}
		}

		if ($format === null) {
			// Because propel.useDateTimeClass is TRUE, we return a DateTime object.
			return $dt;
		} elseif (strpos($format, '%') !== false) {
			return strftime($format, $dt->format('U'));
		} else {
			return $dt->format($format);
		}
	}

	/**
	 * Get the [published] column value.
	 * 
	 * @return     boolean
	 */
	public function getPublished()
	{
		return $this->published;
	}

	/**
	 * Get the [cover] column value.
	 * 
	 * @return     string
	 */
	public function getCover()
	{
		return $this->cover;
	}

	/**
	 * Get the [url] column value.
	 * 
	 * @return     string
	 */
	public function getUrl()
	{
		return $this->url;
	}

	/**
	 * Get the [upload_type] column value.
	 * 
	 * @return     string
	 */
	public function getUploadType()
	{
		return $this->upload_type;
	}

	/**
	 * Get the [uploaded_cover] column value.
	 * 
	 * @return     string
	 */
	public function getUploadedCover()
	{
		return $this->uploaded_cover;
	}

	/**
	 * Get the [uploaded_hpub] column value.
	 * 
	 * @return     string
	 */
	public function getUploadedHpub()
	{
		return $this->uploaded_hpub;
	}

	/**
	 * Get the [uploaded_zip] column value.
	 * 
	 * @return     string
	 */
	public function getUploadedZip()
	{
		return $this->uploaded_zip;
	}

	/**
	 * Get the [allow_notification] column value.
	 * 
	 * @return     boolean
	 */
	public function getAllowNotification()
	{
		return $this->allow_notification;
	}

	/**
	 * Get the [notified] column value.
	 * 
	 * @return     boolean
	 */
	public function getNotified()
	{
		return $this->notified;
	}

	/**
	 * Get the [itunes_include] column value.
	 * 
	 * @return     boolean
	 */
	public function getItunesInclude()
	{
		return $this->itunes_include;
	}

	/**
	 * Get the [itunes_summary] column value.
	 * 
	 * @return     string
	 */
	public function getItunesSummary()
	{
		return $this->itunes_summary;
	}

	/**
	 * Get the [itunes_coverart_url] column value.
	 * 
	 * @return     string
	 */
	public function getItunesCoverartUrl()
	{
		return $this->itunes_coverart_url;
	}

	/**
	 * Get the [optionally formatted] temporal [itunes_published] column value.
	 * 
	 *
	 * @param      string $format The date/time format string (either date()-style or strftime()-style).
	 *							If format is NULL, then the raw DateTime object will be returned.
	 * @return     mixed Formatted date/time value as string or DateTime object (if format is NULL), NULL if column is NULL, and 0 if column value is 0000-00-00 00:00:00
	 * @throws     PropelException - if unable to parse/validate the date/time value.
	 */
	public function getItunesPublished($format = 'Y-m-d H:i:s')
	{
		if ($this->itunes_published === null) {
			return null;
		}


		if ($this->itunes_published === '0000-00-00 00:00:00') {
			// while technically this is not a default value of NULL,
			// this seems to be closest in meaning.
			return null;
		} else {
			try {
				$dt = new DateTime($this->itunes_published);
			} catch (Exception $x) {
				throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->itunes_published, true), $x);
			}
		}

		if ($format === null) {
			// Because propel.useDateTimeClass is TRUE, we return a DateTime object.
			return $dt;
		} elseif (strpos($format, '%') !== false) {
			return strftime($format, $dt->format('U'));
		} else {
			return $dt->format($format);
		}
	}

	/**
	 * Get the [optionally formatted] temporal [itunes_updated] column value.
	 * 
	 *
	 * @param      string $format The date/time format string (either date()-style or strftime()-style).
	 *							If format is NULL, then the raw DateTime object will be returned.
	 * @return     mixed Formatted date/time value as string or DateTime object (if format is NULL), NULL if column is NULL, and 0 if column value is 0000-00-00 00:00:00
	 * @throws     PropelException - if unable to parse/validate the date/time value.
	 */
	public function getItunesUpdated($format = 'Y-m-d H:i:s')
	{
		if ($this->itunes_updated === null) {
			return null;
		}


		if ($this->itunes_updated === '0000-00-00 00:00:00') {
			// while technically this is not a default value of NULL,
			// this seems to be closest in meaning.
			return null;
		} else {
			try {
				$dt = new DateTime($this->itunes_updated);
			} catch (Exception $x) {
				throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->itunes_updated, true), $x);
			}
		}

		if ($format === null) {
			// Because propel.useDateTimeClass is TRUE, we return a DateTime object.
			return $dt;
		} elseif (strpos($format, '%') !== false) {
			return strftime($format, $dt->format('U'));
		} else {
			return $dt->format($format);
		}
	}

	/**
	 * Set the value of [id] column.
	 * 
	 * @param      int $v new value
	 * @return     Issue The current object (for fluent API support)
	 */
	public function setId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->id !== $v) {
			$this->id = $v;
			$this->modifiedColumns[] = IssuePeer::ID;
		}

		return $this;
	} // setId()

	/**
	 * Sets the value of [created_at] column to a normalized version of the date/time value specified.
	 * 
	 * @param      mixed $v string, integer (timestamp), or DateTime value.  Empty string will
	 *						be treated as NULL for temporal objects.
	 * @return     Issue The current object (for fluent API support)
	 */
	public function setCreatedAt($v)
	{
		// we treat '' as NULL for temporal objects because DateTime('') == DateTime('now')
		// -- which is unexpected, to say the least.
		if ($v === null || $v === '') {
			$dt = null;
		} elseif ($v instanceof DateTime) {
			$dt = $v;
		} else {
			// some string/numeric value passed; we normalize that so that we can
			// validate it.
			try {
				if (is_numeric($v)) { // if it's a unix timestamp
					$dt = new DateTime('@'.$v, new DateTimeZone('UTC'));
					// We have to explicitly specify and then change the time zone because of a
					// DateTime bug: http://bugs.php.net/bug.php?id=43003
					$dt->setTimeZone(new DateTimeZone(date_default_timezone_get()));
				} else {
					$dt = new DateTime($v);
				}
			} catch (Exception $x) {
				throw new PropelException('Error parsing date/time value: ' . var_export($v, true), $x);
			}
		}

		if ( $this->created_at !== null || $dt !== null ) {
			// (nested ifs are a little easier to read in this case)

			$currNorm = ($this->created_at !== null && $tmpDt = new DateTime($this->created_at)) ? $tmpDt->format('Y-m-d H:i:s') : null;
			$newNorm = ($dt !== null) ? $dt->format('Y-m-d H:i:s') : null;

			if ( ($currNorm !== $newNorm) // normalized values don't match 
					)
			{
				$this->created_at = ($dt ? $dt->format('Y-m-d H:i:s') : null);
				$this->modifiedColumns[] = IssuePeer::CREATED_AT;
			}
		} // if either are not null

		return $this;
	} // setCreatedAt()

	/**
	 * Sets the value of [updated_at] column to a normalized version of the date/time value specified.
	 * 
	 * @param      mixed $v string, integer (timestamp), or DateTime value.  Empty string will
	 *						be treated as NULL for temporal objects.
	 * @return     Issue The current object (for fluent API support)
	 */
	public function setUpdatedAt($v)
	{
		// we treat '' as NULL for temporal objects because DateTime('') == DateTime('now')
		// -- which is unexpected, to say the least.
		if ($v === null || $v === '') {
			$dt = null;
		} elseif ($v instanceof DateTime) {
			$dt = $v;
		} else {
			// some string/numeric value passed; we normalize that so that we can
			// validate it.
			try {
				if (is_numeric($v)) { // if it's a unix timestamp
					$dt = new DateTime('@'.$v, new DateTimeZone('UTC'));
					// We have to explicitly specify and then change the time zone because of a
					// DateTime bug: http://bugs.php.net/bug.php?id=43003
					$dt->setTimeZone(new DateTimeZone(date_default_timezone_get()));
				} else {
					$dt = new DateTime($v);
				}
			} catch (Exception $x) {
				throw new PropelException('Error parsing date/time value: ' . var_export($v, true), $x);
			}
		}

		if ( $this->updated_at !== null || $dt !== null ) {
			// (nested ifs are a little easier to read in this case)

			$currNorm = ($this->updated_at !== null && $tmpDt = new DateTime($this->updated_at)) ? $tmpDt->format('Y-m-d H:i:s') : null;
			$newNorm = ($dt !== null) ? $dt->format('Y-m-d H:i:s') : null;

			if ( ($currNorm !== $newNorm) // normalized values don't match 
					)
			{
				$this->updated_at = ($dt ? $dt->format('Y-m-d H:i:s') : null);
				$this->modifiedColumns[] = IssuePeer::UPDATED_AT;
			}
		} // if either are not null

		return $this;
	} // setUpdatedAt()

	/**
	 * Set the value of [publication_id] column.
	 * 
	 * @param      int $v new value
	 * @return     Issue The current object (for fluent API support)
	 */
	public function setPublicationId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->publication_id !== $v) {
			$this->publication_id = $v;
			$this->modifiedColumns[] = IssuePeer::PUBLICATION_ID;
		}

		if ($this->aPublication !== null && $this->aPublication->getId() !== $v) {
			$this->aPublication = null;
		}

		return $this;
	} // setPublicationId()

	/**
	 * Set the value of [name] column.
	 * 
	 * @param      string $v new value
	 * @return     Issue The current object (for fluent API support)
	 */
	public function setName($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->name !== $v) {
			$this->name = $v;
			$this->modifiedColumns[] = IssuePeer::NAME;
		}

		return $this;
	} // setName()

	/**
	 * Set the value of [free] column.
	 * 
	 * @param      boolean $v new value
	 * @return     Issue The current object (for fluent API support)
	 */
	public function setFree($v)
	{
		if ($v !== null) {
			$v = (boolean) $v;
		}

		if ($this->free !== $v || $this->isNew()) {
			$this->free = $v;
			$this->modifiedColumns[] = IssuePeer::FREE;
		}

		return $this;
	} // setFree()

	/**
	 * Set the value of [product_id] column.
	 * 
	 * @param      string $v new value
	 * @return     Issue The current object (for fluent API support)
	 */
	public function setProductId($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->product_id !== $v) {
			$this->product_id = $v;
			$this->modifiedColumns[] = IssuePeer::PRODUCT_ID;
		}

		return $this;
	} // setProductId()

	/**
	 * Set the value of [title] column.
	 * 
	 * @param      string $v new value
	 * @return     Issue The current object (for fluent API support)
	 */
	public function setTitle($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->title !== $v) {
			$this->title = $v;
			$this->modifiedColumns[] = IssuePeer::TITLE;
		}

		return $this;
	} // setTitle()

	/**
	 * Set the value of [info] column.
	 * 
	 * @param      string $v new value
	 * @return     Issue The current object (for fluent API support)
	 */
	public function setInfo($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->info !== $v) {
			$this->info = $v;
			$this->modifiedColumns[] = IssuePeer::INFO;
		}

		return $this;
	} // setInfo()

	/**
	 * Sets the value of [date] column to a normalized version of the date/time value specified.
	 * 
	 * @param      mixed $v string, integer (timestamp), or DateTime value.  Empty string will
	 *						be treated as NULL for temporal objects.
	 * @return     Issue The current object (for fluent API support)
	 */
	public function setDate($v)
	{
		// we treat '' as NULL for temporal objects because DateTime('') == DateTime('now')
		// -- which is unexpected, to say the least.
		if ($v === null || $v === '') {
			$dt = null;
		} elseif ($v instanceof DateTime) {
			$dt = $v;
		} else {
			// some string/numeric value passed; we normalize that so that we can
			// validate it.
			try {
				if (is_numeric($v)) { // if it's a unix timestamp
					$dt = new DateTime('@'.$v, new DateTimeZone('UTC'));
					// We have to explicitly specify and then change the time zone because of a
					// DateTime bug: http://bugs.php.net/bug.php?id=43003
					$dt->setTimeZone(new DateTimeZone(date_default_timezone_get()));
				} else {
					$dt = new DateTime($v);
				}
			} catch (Exception $x) {
				throw new PropelException('Error parsing date/time value: ' . var_export($v, true), $x);
			}
		}

		if ( $this->date !== null || $dt !== null ) {
			// (nested ifs are a little easier to read in this case)

			$currNorm = ($this->date !== null && $tmpDt = new DateTime($this->date)) ? $tmpDt->format('Y-m-d') : null;
			$newNorm = ($dt !== null) ? $dt->format('Y-m-d') : null;

			if ( ($currNorm !== $newNorm) // normalized values don't match 
					)
			{
				$this->date = ($dt ? $dt->format('Y-m-d') : null);
				$this->modifiedColumns[] = IssuePeer::DATE;
			}
		} // if either are not null

		return $this;
	} // setDate()

	/**
	 * Set the value of [published] column.
	 * 
	 * @param      boolean $v new value
	 * @return     Issue The current object (for fluent API support)
	 */
	public function setPublished($v)
	{
		if ($v !== null) {
			$v = (boolean) $v;
		}

		if ($this->published !== $v || $this->isNew()) {
			$this->published = $v;
			$this->modifiedColumns[] = IssuePeer::PUBLISHED;
		}

		return $this;
	} // setPublished()

	/**
	 * Set the value of [cover] column.
	 * 
	 * @param      string $v new value
	 * @return     Issue The current object (for fluent API support)
	 */
	public function setCover($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->cover !== $v) {
			$this->cover = $v;
			$this->modifiedColumns[] = IssuePeer::COVER;
		}

		return $this;
	} // setCover()

	/**
	 * Set the value of [url] column.
	 * 
	 * @param      string $v new value
	 * @return     Issue The current object (for fluent API support)
	 */
	public function setUrl($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->url !== $v) {
			$this->url = $v;
			$this->modifiedColumns[] = IssuePeer::URL;
		}

		return $this;
	} // setUrl()

	/**
	 * Set the value of [upload_type] column.
	 * 
	 * @param      string $v new value
	 * @return     Issue The current object (for fluent API support)
	 */
	public function setUploadType($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->upload_type !== $v || $this->isNew()) {
			$this->upload_type = $v;
			$this->modifiedColumns[] = IssuePeer::UPLOAD_TYPE;
		}

		return $this;
	} // setUploadType()

	/**
	 * Set the value of [uploaded_cover] column.
	 * 
	 * @param      string $v new value
	 * @return     Issue The current object (for fluent API support)
	 */
	public function setUploadedCover($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->uploaded_cover !== $v) {
			$this->uploaded_cover = $v;
			$this->modifiedColumns[] = IssuePeer::UPLOADED_COVER;
		}

		return $this;
	} // setUploadedCover()

	/**
	 * Set the value of [uploaded_hpub] column.
	 * 
	 * @param      string $v new value
	 * @return     Issue The current object (for fluent API support)
	 */
	public function setUploadedHpub($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->uploaded_hpub !== $v) {
			$this->uploaded_hpub = $v;
			$this->modifiedColumns[] = IssuePeer::UPLOADED_HPUB;
		}

		return $this;
	} // setUploadedHpub()

	/**
	 * Set the value of [uploaded_zip] column.
	 * 
	 * @param      string $v new value
	 * @return     Issue The current object (for fluent API support)
	 */
	public function setUploadedZip($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->uploaded_zip !== $v) {
			$this->uploaded_zip = $v;
			$this->modifiedColumns[] = IssuePeer::UPLOADED_ZIP;
		}

		return $this;
	} // setUploadedZip()

	/**
	 * Set the value of [allow_notification] column.
	 * 
	 * @param      boolean $v new value
	 * @return     Issue The current object (for fluent API support)
	 */
	public function setAllowNotification($v)
	{
		if ($v !== null) {
			$v = (boolean) $v;
		}

		if ($this->allow_notification !== $v || $this->isNew()) {
			$this->allow_notification = $v;
			$this->modifiedColumns[] = IssuePeer::ALLOW_NOTIFICATION;
		}

		return $this;
	} // setAllowNotification()

	/**
	 * Set the value of [notified] column.
	 * 
	 * @param      boolean $v new value
	 * @return     Issue The current object (for fluent API support)
	 */
	public function setNotified($v)
	{
		if ($v !== null) {
			$v = (boolean) $v;
		}

		if ($this->notified !== $v || $this->isNew()) {
			$this->notified = $v;
			$this->modifiedColumns[] = IssuePeer::NOTIFIED;
		}

		return $this;
	} // setNotified()

	/**
	 * Set the value of [itunes_include] column.
	 * 
	 * @param      boolean $v new value
	 * @return     Issue The current object (for fluent API support)
	 */
	public function setItunesInclude($v)
	{
		if ($v !== null) {
			$v = (boolean) $v;
		}

		if ($this->itunes_include !== $v || $this->isNew()) {
			$this->itunes_include = $v;
			$this->modifiedColumns[] = IssuePeer::ITUNES_INCLUDE;
		}

		return $this;
	} // setItunesInclude()

	/**
	 * Set the value of [itunes_summary] column.
	 * 
	 * @param      string $v new value
	 * @return     Issue The current object (for fluent API support)
	 */
	public function setItunesSummary($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->itunes_summary !== $v) {
			$this->itunes_summary = $v;
			$this->modifiedColumns[] = IssuePeer::ITUNES_SUMMARY;
		}

		return $this;
	} // setItunesSummary()

	/**
	 * Set the value of [itunes_coverart_url] column.
	 * 
	 * @param      string $v new value
	 * @return     Issue The current object (for fluent API support)
	 */
	public function setItunesCoverartUrl($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->itunes_coverart_url !== $v) {
			$this->itunes_coverart_url = $v;
			$this->modifiedColumns[] = IssuePeer::ITUNES_COVERART_URL;
		}

		return $this;
	} // setItunesCoverartUrl()

	/**
	 * Sets the value of [itunes_published] column to a normalized version of the date/time value specified.
	 * 
	 * @param      mixed $v string, integer (timestamp), or DateTime value.  Empty string will
	 *						be treated as NULL for temporal objects.
	 * @return     Issue The current object (for fluent API support)
	 */
	public function setItunesPublished($v)
	{
		// we treat '' as NULL for temporal objects because DateTime('') == DateTime('now')
		// -- which is unexpected, to say the least.
		if ($v === null || $v === '') {
			$dt = null;
		} elseif ($v instanceof DateTime) {
			$dt = $v;
		} else {
			// some string/numeric value passed; we normalize that so that we can
			// validate it.
			try {
				if (is_numeric($v)) { // if it's a unix timestamp
					$dt = new DateTime('@'.$v, new DateTimeZone('UTC'));
					// We have to explicitly specify and then change the time zone because of a
					// DateTime bug: http://bugs.php.net/bug.php?id=43003
					$dt->setTimeZone(new DateTimeZone(date_default_timezone_get()));
				} else {
					$dt = new DateTime($v);
				}
			} catch (Exception $x) {
				throw new PropelException('Error parsing date/time value: ' . var_export($v, true), $x);
			}
		}

		if ( $this->itunes_published !== null || $dt !== null ) {
			// (nested ifs are a little easier to read in this case)

			$currNorm = ($this->itunes_published !== null && $tmpDt = new DateTime($this->itunes_published)) ? $tmpDt->format('Y-m-d H:i:s') : null;
			$newNorm = ($dt !== null) ? $dt->format('Y-m-d H:i:s') : null;

			if ( ($currNorm !== $newNorm) // normalized values don't match 
					)
			{
				$this->itunes_published = ($dt ? $dt->format('Y-m-d H:i:s') : null);
				$this->modifiedColumns[] = IssuePeer::ITUNES_PUBLISHED;
			}
		} // if either are not null

		return $this;
	} // setItunesPublished()

	/**
	 * Sets the value of [itunes_updated] column to a normalized version of the date/time value specified.
	 * 
	 * @param      mixed $v string, integer (timestamp), or DateTime value.  Empty string will
	 *						be treated as NULL for temporal objects.
	 * @return     Issue The current object (for fluent API support)
	 */
	public function setItunesUpdated($v)
	{
		// we treat '' as NULL for temporal objects because DateTime('') == DateTime('now')
		// -- which is unexpected, to say the least.
		if ($v === null || $v === '') {
			$dt = null;
		} elseif ($v instanceof DateTime) {
			$dt = $v;
		} else {
			// some string/numeric value passed; we normalize that so that we can
			// validate it.
			try {
				if (is_numeric($v)) { // if it's a unix timestamp
					$dt = new DateTime('@'.$v, new DateTimeZone('UTC'));
					// We have to explicitly specify and then change the time zone because of a
					// DateTime bug: http://bugs.php.net/bug.php?id=43003
					$dt->setTimeZone(new DateTimeZone(date_default_timezone_get()));
				} else {
					$dt = new DateTime($v);
				}
			} catch (Exception $x) {
				throw new PropelException('Error parsing date/time value: ' . var_export($v, true), $x);
			}
		}

		if ( $this->itunes_updated !== null || $dt !== null ) {
			// (nested ifs are a little easier to read in this case)

			$currNorm = ($this->itunes_updated !== null && $tmpDt = new DateTime($this->itunes_updated)) ? $tmpDt->format('Y-m-d H:i:s') : null;
			$newNorm = ($dt !== null) ? $dt->format('Y-m-d H:i:s') : null;

			if ( ($currNorm !== $newNorm) // normalized values don't match 
					)
			{
				$this->itunes_updated = ($dt ? $dt->format('Y-m-d H:i:s') : null);
				$this->modifiedColumns[] = IssuePeer::ITUNES_UPDATED;
			}
		} // if either are not null

		return $this;
	} // setItunesUpdated()

	/**
	 * Indicates whether the columns in this object are only set to default values.
	 *
	 * This method can be used in conjunction with isModified() to indicate whether an object is both
	 * modified _and_ has some values set which are non-default.
	 *
	 * @return     boolean Whether the columns in this object are only been set with default values.
	 */
	public function hasOnlyDefaultValues()
	{
			if ($this->free !== true) {
				return false;
			}

			if ($this->published !== true) {
				return false;
			}

			if ($this->upload_type !== 'u') {
				return false;
			}

			if ($this->allow_notification !== false) {
				return false;
			}

			if ($this->notified !== false) {
				return false;
			}

			if ($this->itunes_include !== false) {
				return false;
			}

		// otherwise, everything was equal, so return TRUE
		return true;
	} // hasOnlyDefaultValues()

	/**
	 * Hydrates (populates) the object variables with values from the database resultset.
	 *
	 * An offset (0-based "start column") is specified so that objects can be hydrated
	 * with a subset of the columns in the resultset rows.  This is needed, for example,
	 * for results of JOIN queries where the resultset row includes columns from two or
	 * more tables.
	 *
	 * @param      array $row The row returned by PDOStatement->fetch(PDO::FETCH_NUM)
	 * @param      int $startcol 0-based offset column which indicates which restultset column to start with.
	 * @param      boolean $rehydrate Whether this object is being re-hydrated from the database.
	 * @return     int next starting column
	 * @throws     PropelException  - Any caught Exception will be rewrapped as a PropelException.
	 */
	public function hydrate($row, $startcol = 0, $rehydrate = false)
	{
		try {

			$this->id = ($row[$startcol + 0] !== null) ? (int) $row[$startcol + 0] : null;
			$this->created_at = ($row[$startcol + 1] !== null) ? (string) $row[$startcol + 1] : null;
			$this->updated_at = ($row[$startcol + 2] !== null) ? (string) $row[$startcol + 2] : null;
			$this->publication_id = ($row[$startcol + 3] !== null) ? (int) $row[$startcol + 3] : null;
			$this->name = ($row[$startcol + 4] !== null) ? (string) $row[$startcol + 4] : null;
			$this->free = ($row[$startcol + 5] !== null) ? (boolean) $row[$startcol + 5] : null;
			$this->product_id = ($row[$startcol + 6] !== null) ? (string) $row[$startcol + 6] : null;
			$this->title = ($row[$startcol + 7] !== null) ? (string) $row[$startcol + 7] : null;
			$this->info = ($row[$startcol + 8] !== null) ? (string) $row[$startcol + 8] : null;
			$this->date = ($row[$startcol + 9] !== null) ? (string) $row[$startcol + 9] : null;
			$this->published = ($row[$startcol + 10] !== null) ? (boolean) $row[$startcol + 10] : null;
			$this->cover = ($row[$startcol + 11] !== null) ? (string) $row[$startcol + 11] : null;
			$this->url = ($row[$startcol + 12] !== null) ? (string) $row[$startcol + 12] : null;
			$this->upload_type = ($row[$startcol + 13] !== null) ? (string) $row[$startcol + 13] : null;
			$this->uploaded_cover = ($row[$startcol + 14] !== null) ? (string) $row[$startcol + 14] : null;
			$this->uploaded_hpub = ($row[$startcol + 15] !== null) ? (string) $row[$startcol + 15] : null;
			$this->uploaded_zip = ($row[$startcol + 16] !== null) ? (string) $row[$startcol + 16] : null;
			$this->allow_notification = ($row[$startcol + 17] !== null) ? (boolean) $row[$startcol + 17] : null;
			$this->notified = ($row[$startcol + 18] !== null) ? (boolean) $row[$startcol + 18] : null;
			$this->itunes_include = ($row[$startcol + 19] !== null) ? (boolean) $row[$startcol + 19] : null;
			$this->itunes_summary = ($row[$startcol + 20] !== null) ? (string) $row[$startcol + 20] : null;
			$this->itunes_coverart_url = ($row[$startcol + 21] !== null) ? (string) $row[$startcol + 21] : null;
			$this->itunes_published = ($row[$startcol + 22] !== null) ? (string) $row[$startcol + 22] : null;
			$this->itunes_updated = ($row[$startcol + 23] !== null) ? (string) $row[$startcol + 23] : null;
			$this->resetModified();

			$this->setNew(false);

			if ($rehydrate) {
				$this->ensureConsistency();
			}

			// FIXME - using NUM_COLUMNS may be clearer.
			return $startcol + 24; // 24 = IssuePeer::NUM_COLUMNS - IssuePeer::NUM_LAZY_LOAD_COLUMNS).

		} catch (Exception $e) {
			throw new PropelException("Error populating Issue object", $e);
		}
	}

	/**
	 * Checks and repairs the internal consistency of the object.
	 *
	 * This method is executed after an already-instantiated object is re-hydrated
	 * from the database.  It exists to check any foreign keys to make sure that
	 * the objects related to the current object are correct based on foreign key.
	 *
	 * You can override this method in the stub class, but you should always invoke
	 * the base method from the overridden method (i.e. parent::ensureConsistency()),
	 * in case your model changes.
	 *
	 * @throws     PropelException
	 */
	public function ensureConsistency()
	{

		if ($this->aPublication !== null && $this->publication_id !== $this->aPublication->getId()) {
			$this->aPublication = null;
		}
	} // ensureConsistency

	/**
	 * Reloads this object from datastore based on primary key and (optionally) resets all associated objects.
	 *
	 * This will only work if the object has been saved and has a valid primary key set.
	 *
	 * @param      boolean $deep (optional) Whether to also de-associated any related objects.
	 * @param      PropelPDO $con (optional) The PropelPDO connection to use.
	 * @return     void
	 * @throws     PropelException - if this object is deleted, unsaved or doesn't have pk match in db
	 */
	public function reload($deep = false, PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("Cannot reload a deleted object.");
		}

		if ($this->isNew()) {
			throw new PropelException("Cannot reload an unsaved object.");
		}

		if ($con === null) {
			$con = Propel::getConnection(IssuePeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		// We don't need to alter the object instance pool; we're just modifying this instance
		// already in the pool.

		$stmt = IssuePeer::doSelectStmt($this->buildPkeyCriteria(), $con);
		$row = $stmt->fetch(PDO::FETCH_NUM);
		$stmt->closeCursor();
		if (!$row) {
			throw new PropelException('Cannot find matching row in the database to reload object values.');
		}
		$this->hydrate($row, 0, true); // rehydrate

		if ($deep) {  // also de-associate any related objects?

			$this->aPublication = null;
		} // if (deep)
	}

	/**
	 * Removes this object from datastore and sets delete attribute.
	 *
	 * @param      PropelPDO $con
	 * @return     void
	 * @throws     PropelException
	 * @see        BaseObject::setDeleted()
	 * @see        BaseObject::isDeleted()
	 */
	public function delete(PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("This object has already been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(IssuePeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		try {
			$ret = $this->preDelete($con);
			// symfony_behaviors behavior
			foreach (sfMixer::getCallables('BaseIssue:delete:pre') as $callable)
			{
			  if (call_user_func($callable, $this, $con))
			  {
			    $con->commit();
			
			    return;
			  }
			}

			if ($ret) {
				IssuePeer::doDelete($this, $con);
				$this->postDelete($con);
				// symfony_behaviors behavior
				foreach (sfMixer::getCallables('BaseIssue:delete:post') as $callable)
				{
				  call_user_func($callable, $this, $con);
				}

				$this->setDeleted(true);
				$con->commit();
			} else {
				$con->commit();
			}
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Persists this object to the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All modified related objects will also be persisted in the doSave()
	 * method.  This method wraps all precipitate database operations in a
	 * single transaction.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        doSave()
	 */
	public function save(PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("You cannot save an object that has been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(IssuePeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		$isInsert = $this->isNew();
		try {
			$ret = $this->preSave($con);
			// symfony_behaviors behavior
			foreach (sfMixer::getCallables('BaseIssue:save:pre') as $callable)
			{
			  if (is_integer($affectedRows = call_user_func($callable, $this, $con)))
			  {
			    $con->commit();
			
			    return $affectedRows;
			  }
			}

			// symfony_timestampable behavior
			if ($this->isModified() && !$this->isColumnModified(IssuePeer::UPDATED_AT))
			{
			  $this->setUpdatedAt(time());
			}

			if ($isInsert) {
				$ret = $ret && $this->preInsert($con);
				// symfony_timestampable behavior
				if (!$this->isColumnModified(IssuePeer::CREATED_AT))
				{
				  $this->setCreatedAt(time());
				}

			} else {
				$ret = $ret && $this->preUpdate($con);
			}
			if ($ret) {
				$affectedRows = $this->doSave($con);
				if ($isInsert) {
					$this->postInsert($con);
				} else {
					$this->postUpdate($con);
				}
				$this->postSave($con);
				// symfony_behaviors behavior
				foreach (sfMixer::getCallables('BaseIssue:save:post') as $callable)
				{
				  call_user_func($callable, $this, $con, $affectedRows);
				}

				IssuePeer::addInstanceToPool($this);
			} else {
				$affectedRows = 0;
			}
			$con->commit();
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Performs the work of inserting or updating the row in the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All related objects are also updated in this method.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        save()
	 */
	protected function doSave(PropelPDO $con)
	{
		$affectedRows = 0; // initialize var to track total num of affected rows
		if (!$this->alreadyInSave) {
			$this->alreadyInSave = true;

			// We call the save method on the following object(s) if they
			// were passed to this object by their coresponding set
			// method.  This object relates to these object(s) by a
			// foreign key reference.

			if ($this->aPublication !== null) {
				if ($this->aPublication->isModified() || $this->aPublication->isNew()) {
					$affectedRows += $this->aPublication->save($con);
				}
				$this->setPublication($this->aPublication);
			}

			if ($this->isNew() ) {
				$this->modifiedColumns[] = IssuePeer::ID;
			}

			// If this object has been modified, then save it to the database.
			if ($this->isModified()) {
				if ($this->isNew()) {
					$pk = IssuePeer::doInsert($this, $con);
					$affectedRows += 1; // we are assuming that there is only 1 row per doInsert() which
										 // should always be true here (even though technically
										 // BasePeer::doInsert() can insert multiple rows).

					$this->setId($pk);  //[IMV] update autoincrement primary key

					$this->setNew(false);
				} else {
					$affectedRows += IssuePeer::doUpdate($this, $con);
				}

				$this->resetModified(); // [HL] After being saved an object is no longer 'modified'
			}

			$this->alreadyInSave = false;

		}
		return $affectedRows;
	} // doSave()

	/**
	 * Array of ValidationFailed objects.
	 * @var        array ValidationFailed[]
	 */
	protected $validationFailures = array();

	/**
	 * Gets any ValidationFailed objects that resulted from last call to validate().
	 *
	 *
	 * @return     array ValidationFailed[]
	 * @see        validate()
	 */
	public function getValidationFailures()
	{
		return $this->validationFailures;
	}

	/**
	 * Validates the objects modified field values and all objects related to this table.
	 *
	 * If $columns is either a column name or an array of column names
	 * only those columns are validated.
	 *
	 * @param      mixed $columns Column name or an array of column names.
	 * @return     boolean Whether all columns pass validation.
	 * @see        doValidate()
	 * @see        getValidationFailures()
	 */
	public function validate($columns = null)
	{
		$res = $this->doValidate($columns);
		if ($res === true) {
			$this->validationFailures = array();
			return true;
		} else {
			$this->validationFailures = $res;
			return false;
		}
	}

	/**
	 * This function performs the validation work for complex object models.
	 *
	 * In addition to checking the current object, all related objects will
	 * also be validated.  If all pass then <code>true</code> is returned; otherwise
	 * an aggreagated array of ValidationFailed objects will be returned.
	 *
	 * @param      array $columns Array of column names to validate.
	 * @return     mixed <code>true</code> if all validations pass; array of <code>ValidationFailed</code> objets otherwise.
	 */
	protected function doValidate($columns = null)
	{
		if (!$this->alreadyInValidation) {
			$this->alreadyInValidation = true;
			$retval = null;

			$failureMap = array();


			// We call the validate method on the following object(s) if they
			// were passed to this object by their coresponding set
			// method.  This object relates to these object(s) by a
			// foreign key reference.

			if ($this->aPublication !== null) {
				if (!$this->aPublication->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aPublication->getValidationFailures());
				}
			}


			if (($retval = IssuePeer::doValidate($this, $columns)) !== true) {
				$failureMap = array_merge($failureMap, $retval);
			}



			$this->alreadyInValidation = false;
		}

		return (!empty($failureMap) ? $failureMap : true);
	}

	/**
	 * Retrieves a field from the object by name passed in as a string.
	 *
	 * @param      string $name name
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     mixed Value of field.
	 */
	public function getByName($name, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = IssuePeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		$field = $this->getByPosition($pos);
		return $field;
	}

	/**
	 * Retrieves a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @return     mixed Value of field at $pos
	 */
	public function getByPosition($pos)
	{
		switch($pos) {
			case 0:
				return $this->getId();
				break;
			case 1:
				return $this->getCreatedAt();
				break;
			case 2:
				return $this->getUpdatedAt();
				break;
			case 3:
				return $this->getPublicationId();
				break;
			case 4:
				return $this->getName();
				break;
			case 5:
				return $this->getFree();
				break;
			case 6:
				return $this->getProductId();
				break;
			case 7:
				return $this->getTitle();
				break;
			case 8:
				return $this->getInfo();
				break;
			case 9:
				return $this->getDate();
				break;
			case 10:
				return $this->getPublished();
				break;
			case 11:
				return $this->getCover();
				break;
			case 12:
				return $this->getUrl();
				break;
			case 13:
				return $this->getUploadType();
				break;
			case 14:
				return $this->getUploadedCover();
				break;
			case 15:
				return $this->getUploadedHpub();
				break;
			case 16:
				return $this->getUploadedZip();
				break;
			case 17:
				return $this->getAllowNotification();
				break;
			case 18:
				return $this->getNotified();
				break;
			case 19:
				return $this->getItunesInclude();
				break;
			case 20:
				return $this->getItunesSummary();
				break;
			case 21:
				return $this->getItunesCoverartUrl();
				break;
			case 22:
				return $this->getItunesPublished();
				break;
			case 23:
				return $this->getItunesUpdated();
				break;
			default:
				return null;
				break;
		} // switch()
	}

	/**
	 * Exports the object as an array.
	 *
	 * You can specify the key type of the array by passing one of the class
	 * type constants.
	 *
	 * @param      string $keyType (optional) One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                        BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM. Defaults to BasePeer::TYPE_PHPNAME.
	 * @param      boolean $includeLazyLoadColumns (optional) Whether to include lazy loaded columns.  Defaults to TRUE.
	 * @return     an associative array containing the field names (as keys) and field values
	 */
	public function toArray($keyType = BasePeer::TYPE_PHPNAME, $includeLazyLoadColumns = true)
	{
		$keys = IssuePeer::getFieldNames($keyType);
		$result = array(
			$keys[0] => $this->getId(),
			$keys[1] => $this->getCreatedAt(),
			$keys[2] => $this->getUpdatedAt(),
			$keys[3] => $this->getPublicationId(),
			$keys[4] => $this->getName(),
			$keys[5] => $this->getFree(),
			$keys[6] => $this->getProductId(),
			$keys[7] => $this->getTitle(),
			$keys[8] => $this->getInfo(),
			$keys[9] => $this->getDate(),
			$keys[10] => $this->getPublished(),
			$keys[11] => $this->getCover(),
			$keys[12] => $this->getUrl(),
			$keys[13] => $this->getUploadType(),
			$keys[14] => $this->getUploadedCover(),
			$keys[15] => $this->getUploadedHpub(),
			$keys[16] => $this->getUploadedZip(),
			$keys[17] => $this->getAllowNotification(),
			$keys[18] => $this->getNotified(),
			$keys[19] => $this->getItunesInclude(),
			$keys[20] => $this->getItunesSummary(),
			$keys[21] => $this->getItunesCoverartUrl(),
			$keys[22] => $this->getItunesPublished(),
			$keys[23] => $this->getItunesUpdated(),
		);
		return $result;
	}

	/**
	 * Sets a field from the object by name passed in as a string.
	 *
	 * @param      string $name peer name
	 * @param      mixed $value field value
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     void
	 */
	public function setByName($name, $value, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = IssuePeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		return $this->setByPosition($pos, $value);
	}

	/**
	 * Sets a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @param      mixed $value field value
	 * @return     void
	 */
	public function setByPosition($pos, $value)
	{
		switch($pos) {
			case 0:
				$this->setId($value);
				break;
			case 1:
				$this->setCreatedAt($value);
				break;
			case 2:
				$this->setUpdatedAt($value);
				break;
			case 3:
				$this->setPublicationId($value);
				break;
			case 4:
				$this->setName($value);
				break;
			case 5:
				$this->setFree($value);
				break;
			case 6:
				$this->setProductId($value);
				break;
			case 7:
				$this->setTitle($value);
				break;
			case 8:
				$this->setInfo($value);
				break;
			case 9:
				$this->setDate($value);
				break;
			case 10:
				$this->setPublished($value);
				break;
			case 11:
				$this->setCover($value);
				break;
			case 12:
				$this->setUrl($value);
				break;
			case 13:
				$this->setUploadType($value);
				break;
			case 14:
				$this->setUploadedCover($value);
				break;
			case 15:
				$this->setUploadedHpub($value);
				break;
			case 16:
				$this->setUploadedZip($value);
				break;
			case 17:
				$this->setAllowNotification($value);
				break;
			case 18:
				$this->setNotified($value);
				break;
			case 19:
				$this->setItunesInclude($value);
				break;
			case 20:
				$this->setItunesSummary($value);
				break;
			case 21:
				$this->setItunesCoverartUrl($value);
				break;
			case 22:
				$this->setItunesPublished($value);
				break;
			case 23:
				$this->setItunesUpdated($value);
				break;
		} // switch()
	}

	/**
	 * Populates the object using an array.
	 *
	 * This is particularly useful when populating an object from one of the
	 * request arrays (e.g. $_POST).  This method goes through the column
	 * names, checking to see whether a matching key exists in populated
	 * array. If so the setByName() method is called for that column.
	 *
	 * You can specify the key type of the array by additionally passing one
	 * of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME,
	 * BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM.
	 * The default key type is the column's phpname (e.g. 'AuthorId')
	 *
	 * @param      array  $arr     An array to populate the object from.
	 * @param      string $keyType The type of keys the array uses.
	 * @return     void
	 */
	public function fromArray($arr, $keyType = BasePeer::TYPE_PHPNAME)
	{
		$keys = IssuePeer::getFieldNames($keyType);

		if (array_key_exists($keys[0], $arr)) $this->setId($arr[$keys[0]]);
		if (array_key_exists($keys[1], $arr)) $this->setCreatedAt($arr[$keys[1]]);
		if (array_key_exists($keys[2], $arr)) $this->setUpdatedAt($arr[$keys[2]]);
		if (array_key_exists($keys[3], $arr)) $this->setPublicationId($arr[$keys[3]]);
		if (array_key_exists($keys[4], $arr)) $this->setName($arr[$keys[4]]);
		if (array_key_exists($keys[5], $arr)) $this->setFree($arr[$keys[5]]);
		if (array_key_exists($keys[6], $arr)) $this->setProductId($arr[$keys[6]]);
		if (array_key_exists($keys[7], $arr)) $this->setTitle($arr[$keys[7]]);
		if (array_key_exists($keys[8], $arr)) $this->setInfo($arr[$keys[8]]);
		if (array_key_exists($keys[9], $arr)) $this->setDate($arr[$keys[9]]);
		if (array_key_exists($keys[10], $arr)) $this->setPublished($arr[$keys[10]]);
		if (array_key_exists($keys[11], $arr)) $this->setCover($arr[$keys[11]]);
		if (array_key_exists($keys[12], $arr)) $this->setUrl($arr[$keys[12]]);
		if (array_key_exists($keys[13], $arr)) $this->setUploadType($arr[$keys[13]]);
		if (array_key_exists($keys[14], $arr)) $this->setUploadedCover($arr[$keys[14]]);
		if (array_key_exists($keys[15], $arr)) $this->setUploadedHpub($arr[$keys[15]]);
		if (array_key_exists($keys[16], $arr)) $this->setUploadedZip($arr[$keys[16]]);
		if (array_key_exists($keys[17], $arr)) $this->setAllowNotification($arr[$keys[17]]);
		if (array_key_exists($keys[18], $arr)) $this->setNotified($arr[$keys[18]]);
		if (array_key_exists($keys[19], $arr)) $this->setItunesInclude($arr[$keys[19]]);
		if (array_key_exists($keys[20], $arr)) $this->setItunesSummary($arr[$keys[20]]);
		if (array_key_exists($keys[21], $arr)) $this->setItunesCoverartUrl($arr[$keys[21]]);
		if (array_key_exists($keys[22], $arr)) $this->setItunesPublished($arr[$keys[22]]);
		if (array_key_exists($keys[23], $arr)) $this->setItunesUpdated($arr[$keys[23]]);
	}

	/**
	 * Build a Criteria object containing the values of all modified columns in this object.
	 *
	 * @return     Criteria The Criteria object containing all modified values.
	 */
	public function buildCriteria()
	{
		$criteria = new Criteria(IssuePeer::DATABASE_NAME);

		if ($this->isColumnModified(IssuePeer::ID)) $criteria->add(IssuePeer::ID, $this->id);
		if ($this->isColumnModified(IssuePeer::CREATED_AT)) $criteria->add(IssuePeer::CREATED_AT, $this->created_at);
		if ($this->isColumnModified(IssuePeer::UPDATED_AT)) $criteria->add(IssuePeer::UPDATED_AT, $this->updated_at);
		if ($this->isColumnModified(IssuePeer::PUBLICATION_ID)) $criteria->add(IssuePeer::PUBLICATION_ID, $this->publication_id);
		if ($this->isColumnModified(IssuePeer::NAME)) $criteria->add(IssuePeer::NAME, $this->name);
		if ($this->isColumnModified(IssuePeer::FREE)) $criteria->add(IssuePeer::FREE, $this->free);
		if ($this->isColumnModified(IssuePeer::PRODUCT_ID)) $criteria->add(IssuePeer::PRODUCT_ID, $this->product_id);
		if ($this->isColumnModified(IssuePeer::TITLE)) $criteria->add(IssuePeer::TITLE, $this->title);
		if ($this->isColumnModified(IssuePeer::INFO)) $criteria->add(IssuePeer::INFO, $this->info);
		if ($this->isColumnModified(IssuePeer::DATE)) $criteria->add(IssuePeer::DATE, $this->date);
		if ($this->isColumnModified(IssuePeer::PUBLISHED)) $criteria->add(IssuePeer::PUBLISHED, $this->published);
		if ($this->isColumnModified(IssuePeer::COVER)) $criteria->add(IssuePeer::COVER, $this->cover);
		if ($this->isColumnModified(IssuePeer::URL)) $criteria->add(IssuePeer::URL, $this->url);
		if ($this->isColumnModified(IssuePeer::UPLOAD_TYPE)) $criteria->add(IssuePeer::UPLOAD_TYPE, $this->upload_type);
		if ($this->isColumnModified(IssuePeer::UPLOADED_COVER)) $criteria->add(IssuePeer::UPLOADED_COVER, $this->uploaded_cover);
		if ($this->isColumnModified(IssuePeer::UPLOADED_HPUB)) $criteria->add(IssuePeer::UPLOADED_HPUB, $this->uploaded_hpub);
		if ($this->isColumnModified(IssuePeer::UPLOADED_ZIP)) $criteria->add(IssuePeer::UPLOADED_ZIP, $this->uploaded_zip);
		if ($this->isColumnModified(IssuePeer::ALLOW_NOTIFICATION)) $criteria->add(IssuePeer::ALLOW_NOTIFICATION, $this->allow_notification);
		if ($this->isColumnModified(IssuePeer::NOTIFIED)) $criteria->add(IssuePeer::NOTIFIED, $this->notified);
		if ($this->isColumnModified(IssuePeer::ITUNES_INCLUDE)) $criteria->add(IssuePeer::ITUNES_INCLUDE, $this->itunes_include);
		if ($this->isColumnModified(IssuePeer::ITUNES_SUMMARY)) $criteria->add(IssuePeer::ITUNES_SUMMARY, $this->itunes_summary);
		if ($this->isColumnModified(IssuePeer::ITUNES_COVERART_URL)) $criteria->add(IssuePeer::ITUNES_COVERART_URL, $this->itunes_coverart_url);
		if ($this->isColumnModified(IssuePeer::ITUNES_PUBLISHED)) $criteria->add(IssuePeer::ITUNES_PUBLISHED, $this->itunes_published);
		if ($this->isColumnModified(IssuePeer::ITUNES_UPDATED)) $criteria->add(IssuePeer::ITUNES_UPDATED, $this->itunes_updated);

		return $criteria;
	}

	/**
	 * Builds a Criteria object containing the primary key for this object.
	 *
	 * Unlike buildCriteria() this method includes the primary key values regardless
	 * of whether or not they have been modified.
	 *
	 * @return     Criteria The Criteria object containing value(s) for primary key(s).
	 */
	public function buildPkeyCriteria()
	{
		$criteria = new Criteria(IssuePeer::DATABASE_NAME);

		$criteria->add(IssuePeer::ID, $this->id);

		return $criteria;
	}

	/**
	 * Returns the primary key for this object (row).
	 * @return     int
	 */
	public function getPrimaryKey()
	{
		return $this->getId();
	}

	/**
	 * Generic method to set the primary key (id column).
	 *
	 * @param      int $key Primary key.
	 * @return     void
	 */
	public function setPrimaryKey($key)
	{
		$this->setId($key);
	}

	/**
	 * Sets contents of passed object to values from current object.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      object $copyObj An object of Issue (or compatible) type.
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @throws     PropelException
	 */
	public function copyInto($copyObj, $deepCopy = false)
	{

		$copyObj->setCreatedAt($this->created_at);

		$copyObj->setUpdatedAt($this->updated_at);

		$copyObj->setPublicationId($this->publication_id);

		$copyObj->setName($this->name);

		$copyObj->setFree($this->free);

		$copyObj->setProductId($this->product_id);

		$copyObj->setTitle($this->title);

		$copyObj->setInfo($this->info);

		$copyObj->setDate($this->date);

		$copyObj->setPublished($this->published);

		$copyObj->setCover($this->cover);

		$copyObj->setUrl($this->url);

		$copyObj->setUploadType($this->upload_type);

		$copyObj->setUploadedCover($this->uploaded_cover);

		$copyObj->setUploadedHpub($this->uploaded_hpub);

		$copyObj->setUploadedZip($this->uploaded_zip);

		$copyObj->setAllowNotification($this->allow_notification);

		$copyObj->setNotified($this->notified);

		$copyObj->setItunesInclude($this->itunes_include);

		$copyObj->setItunesSummary($this->itunes_summary);

		$copyObj->setItunesCoverartUrl($this->itunes_coverart_url);

		$copyObj->setItunesPublished($this->itunes_published);

		$copyObj->setItunesUpdated($this->itunes_updated);


		$copyObj->setNew(true);

		$copyObj->setId(NULL); // this is a auto-increment column, so set to default value

	}

	/**
	 * Makes a copy of this object that will be inserted as a new row in table when saved.
	 * It creates a new object filling in the simple attributes, but skipping any primary
	 * keys that are defined for the table.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @return     Issue Clone of current object.
	 * @throws     PropelException
	 */
	public function copy($deepCopy = false)
	{
		// we use get_class(), because this might be a subclass
		$clazz = get_class($this);
		$copyObj = new $clazz();
		$this->copyInto($copyObj, $deepCopy);
		return $copyObj;
	}

	/**
	 * Returns a peer instance associated with this om.
	 *
	 * Since Peer classes are not to have any instance attributes, this method returns the
	 * same instance for all member of this class. The method could therefore
	 * be static, but this would prevent one from overriding the behavior.
	 *
	 * @return     IssuePeer
	 */
	public function getPeer()
	{
		if (self::$peer === null) {
			self::$peer = new IssuePeer();
		}
		return self::$peer;
	}

	/**
	 * Declares an association between this object and a Publication object.
	 *
	 * @param      Publication $v
	 * @return     Issue The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setPublication(Publication $v = null)
	{
		if ($v === null) {
			$this->setPublicationId(NULL);
		} else {
			$this->setPublicationId($v->getId());
		}

		$this->aPublication = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the Publication object, it will not be re-added.
		if ($v !== null) {
			$v->addIssue($this);
		}

		return $this;
	}


	/**
	 * Get the associated Publication object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     Publication The associated Publication object.
	 * @throws     PropelException
	 */
	public function getPublication(PropelPDO $con = null)
	{
		if ($this->aPublication === null && ($this->publication_id !== null)) {
			$this->aPublication = PublicationPeer::retrieveByPk($this->publication_id);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->aPublication->addIssues($this);
			 */
		}
		return $this->aPublication;
	}

	/**
	 * Resets all collections of referencing foreign keys.
	 *
	 * This method is a user-space workaround for PHP's inability to garbage collect objects
	 * with circular references.  This is currently necessary when using Propel in certain
	 * daemon or large-volumne/high-memory operations.
	 *
	 * @param      boolean $deep Whether to also clear the references on all associated objects.
	 */
	public function clearAllReferences($deep = false)
	{
		if ($deep) {
		} // if ($deep)

			$this->aPublication = null;
	}

	// symfony_behaviors behavior
	
	/**
	 * Calls methods defined via {@link sfMixer}.
	 */
	public function __call($method, $arguments)
	{
	  if (!$callable = sfMixer::getCallable('BaseIssue:'.$method))
	  {
	    throw new sfException(sprintf('Call to undefined method BaseIssue::%s', $method));
	  }
	
	  array_unshift($arguments, $this);
	
	  return call_user_func_array($callable, $arguments);
	}

} // BaseIssue
