<?php


/**
 * Skeleton subclass for performing query and update operations on the 'apns_messages' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Wed May 15 17:29:35 2013
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class ApnsMessagePeer extends BaseApnsMessagePeer {

  const STATUS_QUEUED = 'queued';
  const STATUS_DELIVERED = 'delivered';
  const STATUS_FAILED = 'failed';

  public static function getMessageQueueCount()
  {
    $c = new Criteria();
    $c->add(self::STATUS, self::STATUS_QUEUED);
    return self::doCount($c);
  }

} // ApnsMessagePeer
