<?php


/**
 * Skeleton subclass for performing query and update operations on the 'apns_devices' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Wed May 15 17:29:35 2013
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class ApnsDevicePeer extends BaseApnsDevicePeer {

  const STATUS_ACTIVE = 'active';
  const STATUS_UNINSTALLED = 'uninstalled';

  public static function retrieveUnique($app_id, $user_id)
  {
    $c = new Criteria();
    $c->add(self::APPNAME, $app_id);
    $c->add(self::DEVICEUID, $user_id);

    $v = self::doSelectOne($c);
    return $v;
  }

} // ApnsDevicePeer
