<?php


/**
 * Skeleton subclass for representing a row from the 'apns_messages' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Wed May 15 17:29:35 2013
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class ApnsMessage extends BaseApnsMessage {

	/**
	 * Initializes internal state of ApnsMessage object.
	 * @see        parent::__construct()
	 */
	public function __construct()
	{
		// Make sure that parent constructor is always invoked, since that
		// is where any default values for this object are set.
		parent::__construct();
	}

  public function preInsert(PropelPDO $con = null)
  {
    $this->setCreated(time());
    $this->setModified(time());

    return true;
  }

  public function preUpdate(PropelPDO $con = null)
  {
    $this->setModified(time());

    return true;
  }

} // ApnsMessage
