<?php


/**
 * Skeleton subclass for performing query and update operations on the 'publication' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Tue May 14 18:14:52 2013
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class PublicationPeer extends BasePublicationPeer {

  const ITUNES_SANDBOX = 'sandbox';
  const ITUNES_PRODUCTION = 'production';
  const SUBSCRIPTION_ALL = 'all';
  const SUBSCRIPTION_TERM = 'term';

  public static function retrieveByApplicationId($app_id)
  {
    $c = new Criteria();
    $c->add(PublicationPeer::APPLICATION_ID, $app_id);
    $c->addDescendingOrderByColumn(PublicationPeer::ID);

    $v = PublicationPeer::doSelectOne($c);
    return $v;
  }

  public static function isDebug($app_id)
  {
    if ($p = self::retrieveByApplicationId($app_id)) {
      return $p->getDevelopmentMode();
    }
  }

} // PublicationPeer
