<?php


/**
 * Skeleton subclass for performing query and update operations on the 'purchase' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Wed May 15 17:26:04 2013
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class PurchasePeer extends BasePurchasePeer {

  public static function isPurchased($app_id, $user_id, $product_id)
  {
    $c = new Criteria();
    $c->add(PurchasePeer::APPLICATION_ID, $app_id);
    $c->add(PurchasePeer::USER_ID, $user_id);
    $c->add(PurchasePeer::PRODUCT_ID, $product_id);

    $count = PurchasePeer::doCount($c);

    return $count > 0;
  }

} // PurchasePeer
