<?php


/**
 * Skeleton subclass for representing a row from the 'receipt' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Wed May 15 17:26:04 2013
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class Receipt extends BaseReceipt {

	/**
	 * Initializes internal state of Receipt object.
	 * @see        parent::__construct()
	 */
	public function __construct()
	{
		// Make sure that parent constructor is always invoked, since that
		// is where any default values for this object are set.
		parent::__construct();
	}

  public function getPublicationName()
  {
    $o = PublicationPeer::retrieveByApplicationId($this->application_id);
    if ($o) {
      return $o->getName();
    }
  }

} // Receipt
