<?php


/**
 * Skeleton subclass for representing a row from the 'subscription' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Wed May 15 17:26:04 2013
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class Subscription extends BaseSubscription {

  /**
   * Get the current time interval between the last validation and expiration
   *
   * @return DateInterval
   */
  public function getInterval()
  {
    $dateLastValidated = new DateTime($this->getLastValidated('Y-m-d H:i:s'));
    $dateExpiration = new DateTime($this->getExpirationDate('Y-m-d H:i:s'));
    $dateCurrent = new DateTime('now');
    $interval = $dateCurrent->diff($dateLastValidated);

    return $interval;
  }

  public function getPublication()
  {
    return PublicationPeer::retrieveByApplicationId($this->getApplicationId());
  }

} // Subscription
